### ISSUE TITLE
Fresh install of ctfd crashes before it can start properly (DistributionNotFound)

### ISSUE THREAD

**Issue by narhen** [CTFd/CTFd#1023]
**Environment**:

  - CTFd Version/Commit: e978867a2f63349f41e696d2a23171e2256babb2
  - Operating System:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```
Docker version:
```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
  - Web Browser and Version: Not relevant

**What happened?**
Fetched a fresh copy of ctfd and deployed it with docker.
The database and cache starts fine, however ctfd crashes (`DistributionNotFound`) right after it starts listening on port 8000.

**What did you expect to happen?**
Expected all three services to start normally and ctfd to not crash, so that I can set up the ctf with a browser.

**How to reproduce your issue**
1. `$ git clone https://github.com/CTFd/CTFd.git`
2. navigate into CTFd and run `docker-compose up -d`
3. watch the log of the `ctfd_ctfd_1 container` and observe it crash after waiting for the database is ready and it starts listening on port 8000.

(I have no other docker containers exposing anything on port 8000)

**Any associated stack traces or error logs**
ctfd log:
```
Waiting for db: to be ready
.........................................................................................................................db is ready
 * Loaded module, <module 'CTFd.plugins.challenges' from '/opt/CTFd/CTFd/plugins/challenges/__init__.py'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/opt/CTFd/CTFd/plugins/dynamic_challenges/__init__.py'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/opt/CTFd/CTFd/plugins/flags/__init__.py'>
Starting CTFd
[2019-06-09 15:24:43 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-06-09 15:24:43 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-06-09 15:24:43 +0000] [1] [INFO] Using worker: gevent
[2019-06-09 15:24:43 +0000] [281] [INFO] Booting worker with pid: 281
[2019-06-09 15:24:43 +0000] [281] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 196, in init_process
    self.patch()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 65, in patch
    monkey.patch_all(subprocess=True)
  File "/usr/local/lib/python2.7/site-packages/gevent/monkey.py", line 966, in patch_all
    _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
  File "/usr/local/lib/python2.7/site-packages/gevent/monkey.py", line 168, in _notify_patch
    notify_and_call_entry_points(event)
  File "/usr/local/lib/python2.7/site-packages/gevent/events.py", line 112, in notify_and_call_entry_points
    subscriber = plugin.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'psutil; platform_python_implementation == "CPython" or sys_platform != "win32" and extra == "test"' distribution was not found and is required by the application
[2019-06-09 15:24:43 +0000] [281] [INFO] Worker exiting (pid: 281)
[2019-06-09 15:24:43 +0000] [1] [INFO] Shutting down: Master
[2019-06-09 15:24:43 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by ColdHeat** [comment]
I wasn't able to reproduce this. Could you try building with `--no-cache`?

```
~/Repositories/CTFd master*
❯ docker-compose build --no-cache && docker-compose up
db uses an image, skipping
cache uses an image, skipping
Building ctfd
Step 1/15 : FROM python:2.7-alpine
 ---> ee70cb11da0d
Step 2/15 : RUN apk update &&     apk add python python-dev linux-headers libffi-dev gcc make musl-dev py-pip mysql-client git openssl-dev
 ---> Running in 6f6f1276a696
...
...
...
...
Starting ctfd_db_1    ... done
Starting ctfd_cache_1 ... done
Recreating ctfd_ctfd_1 ... done
Attaching to ctfd_cache_1, ctfd_db_1, ctfd_ctfd_1
db_1     | Initializing database
cache_1  | 1:C 11 Jun 04:41:59.880 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache_1  | 1:C 11 Jun 04:41:59.884 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
cache_1  | 1:C 11 Jun 04:41:59.884 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
ctfd_1   | Waiting for db: to be ready
cache_1  | 1:M 11 Jun 04:41:59.888 * Running mode=standalone, port=6379.
cache_1  | 1:M 11 Jun 04:41:59.888 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
cache_1  | 1:M 11 Jun 04:41:59.888 # Server initialized
cache_1  | 1:M 11 Jun 04:41:59.889 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
cache_1  | 1:M 11 Jun 04:41:59.889 * Ready to accept connections
db_1     |
db_1     |
db_1     | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
db_1     | To do so, start the server, then issue the following commands:
db_1     |
db_1     | '/usr/bin/mysqladmin' -u root password 'new-password'
db_1     | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
db_1     |
db_1     | Alternatively you can run:
db_1     | '/usr/bin/mysql_secure_installation'
db_1     |
...
...
...
db_1     | 2019-06-11  4:42:26 0 [Note] InnoDB: Buffer pool(s) load completed at 190611  4:42:26
db_1     | 2019-06-11  4:42:26 0 [Note] Server socket created on IP: '::'.
db_1     | 2019-06-11  4:42:26 0 [Warning] 'proxies_priv' entry '@% root@216ba5777c7b' ignored in --skip-name-resolve mode.
db_1     | 2019-06-11  4:42:26 0 [Note] mysqld: ready for connections.
db_1     | Version: '10.4.4-MariaDB-1:10.4.4+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
ctfd_1   | ..........................db is ready
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.challenges' from '/opt/CTFd/CTFd/plugins/challenges/__init__.pyc'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/opt/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.flags' from '/opt/CTFd/CTFd/plugins/flags/__init__.pyc'>
ctfd_1   | Starting CTFd
ctfd_1   | [2019-06-11 04:42:32 +0000] [1] [INFO] Starting gunicorn 19.9.0
ctfd_1   | [2019-06-11 04:42:32 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
ctfd_1   | [2019-06-11 04:42:32 +0000] [1] [INFO] Using worker: gevent
ctfd_1   | [2019-06-11 04:42:32 +0000] [86] [INFO] Booting worker with pid: 86
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.challenges' from '/opt/CTFd/CTFd/plugins/challenges/__init__.pyc'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/opt/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.flags' from '/opt/CTFd/CTFd/plugins/flags/__init__.pyc'>
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET / HTTP/1.1" 302 219 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /setup HTTP/1.1" 200 5904 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/css/vendor/font-awesome/fontawesome-fonts.css HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/css/base.css HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/css/sticky-footer.css HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/css/vendor/font.css HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/css/vendor/font-awesome/fontawesome-all.min.css HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/css/vendor/bootstrap.min.css HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/css/jumbotron.css HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/vendor/promise-polyfill.min.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/vendor/eventsource.min.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/vendor/fetch.min.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/vendor/moment.min.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/vendor/nunjucks.min.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/vendor/jquery.min.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/CTFd.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/vendor/bootstrap.bundle.min.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/vendor/howler.min.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/vendor/markdown-it.min.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/vendor/window-controller.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/style.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/utils.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /static/user.css HTTP/1.1" 302 219 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/ezq.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/js/events.js HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /setup HTTP/1.1" 200 5904 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/sounds/notification.webm HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:39 +0000] "GET /themes/core/static/img/favicon.ico HTTP/1.1" 200 0 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:40 +0000] "GET /events HTTP/1.1" 302 219 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
ctfd_1   | 172.20.0.1 - - [11/Jun/2019:04:43:40 +0000] "GET /setup HTTP/1.1" 200 5904 "http://localhost:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
```
