### ISSUE TITLE
Migrating database from older versions 1.2.0 > 2.0

### ISSUE THREAD

**Issue by RamiAltai** [CTFd/CTFd#1065]
I've been working on a project and i'm currently stuck. 
the project was originally implemented on the CTFd 1.2.0, and a tons of issues been popping up since it is quite outdated. 

Currently I can't get the copy that got my data up and running nor a fresh CTFd 1.2.0 instance, and my data base is a hostage. How can I get my data base or migrate it to a newer version?

I've seen the 1_2_0_upgrade_2_0_0.py script in the latest release, but I couldn't figure out how to use it and it isn't mentioned anywhere in the documentation other that this "CTFd makes use of alembic and Flask-Migrate to perform database migrations between versions."

**Comment by ColdHeat** [comment]
The docs do need a section on migrating from 1.2.0 to 2.0.0, it's something that's slipped my mind but if you want to PR it in that'd be nice. 

There are some notes about it in the CHANGELOG here: https://github.com/CTFd/CTFd/blob/master/CHANGELOG.md#200--2018-12-02

**Comment by RamiAltai** [comment]
I followed the steps, and I think it's worth mentioning that in the original one, I used the basic deployment steps (docker-compose up) without customizing much. 

"Set the DATABASE_URL in CTFd/config.py to point to your existing CTFd database." i had to change nothing since bot files before and after the pull were identical

"Run the upgrade script from the CTFd root folder i.e. python migrations/1_2_0_upgrade_2_0_0.py." I noticed some missing requirements so I ran (pip install -r requirements.txt)

now it's reporting another missing library which is CTFd

"""
python 1_2_0_upgrade_2_0_0.py
----------------------------------------------------------------
Traceback (most recent call last):
  File "1_2_0_upgrade_2_0_0.py", line 14, in <module>
    from CTFd import config, create_app
ImportError: No module named CTFd
"""

**Comment by RamiAltai** [comment]
I followed the steps, and I think it's worth mentioning that in the original one, I used the basic deployment steps (docker-compose up) without customizing much.

"Set the DATABASE_URL in CTFd/config.py to point to your existing CTFd database." i had to change nothing since bot files before and after the pull were identical

"Run the upgrade script from the CTFd root folder i.e. python migrations/1_2_0_upgrade_2_0_0.py." I noticed some missing requirements so I ran (pip install -r requirements.txt)

and it ran smoothly after running it from the main directory or the project, without pointing to any missing libraries.
"""
 python migrations/1_2_0_upgrade_2_0_0.py
---------------------
MIGRATING Challenges
Traceback (most recent call last):
  File "migrations/1_2_0_upgrade_2_0_0.py", line 71, in <module>
    for challenge in old_data['challenges']:
KeyError: 'challenges'
"""

**Comment by RamiAltai** [comment]
after re-running the script it got stuck on the following error 

Traceback (most recent call last):
  File "migrations/1_2_0_upgrade_2_0_0.py", line 94, in <module>
    for key in old_data['keys']:
KeyError: 'keys'

**Comment by RamiAltai** [comment]
After quite a bit of tweaking and tooling around with the code, I managed to get around the errors, but now when I'm running the (sudo docker-compose up) the following shows up 

db_1     | 2019-07-22 12:25:39 0 [Note] mysqld: ready for connections.
db_1     | Version: '10.4.6-MariaDB-1:10.4.6+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
ctfd_1   | .db is ready
ctfd_1   | No handlers could be found for logger "root"
ctfd_ctfd_1 exited with code 1
ctfd_1   | Waiting for db: to be ready
ctfd_1   | .db is ready
ctfd_1   | No handlers could be found for logger "root"
ctfd_1   | Waiting for db: to be ready
ctfd_1   | db is ready


and it keeps looping through the error
