### ISSUE TITLE
Docker Composition Exception

### ISSUE THREAD

**Issue by lococafe** [CTFd/CTFd#1089]
- CTFd Version/Commit: Latest
  - Operating System: Windows 10 Pro/Docker CE
  - Web Browser and Version: Not Relevant

**What happened?**
Had good installation of Docker, ran:
```
git clone https://github.com/CTFd/CTFd.git
cd CTFd/
docker-compose up
```

Ran into exceptions at multiple points, as below.

**What did you expect to happen?**
Brilliance/CTFd to to be running

**How to reproduce your issue**
Repeatedly followed same steps in same environment

**Any associated stack traces or error logs**

```
C:\Users\User\Downloads\newd\CTFd>docker-compose up
Starting ctfd_db_1    ... done                                                                                          Starting ctfd_cache_1 ... done                                                                                          Starting ctfd_ctfd_1  ... done                                                                                          Attaching to ctfd_cache_1, ctfd_db_1, ctfd_ctfd_1
cache_1  | 1:C 20 Aug 06:03:06.693 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache_1  | 1:C 20 Aug 06:03:06.693 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
cache_1  | 1:C 20 Aug 06:03:06.693 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cache_1  | 1:M 20 Aug 06:03:06.695 * Running mode=standalone, port=6379.
cache_1  | 1:M 20 Aug 06:03:06.695 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
cache_1  | 1:M 20 Aug 06:03:06.695 # Server initialized
cache_1  | 1:M 20 Aug 06:03:06.695 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
db_1     | Initializing database
cache_1  | 1:M 20 Aug 06:03:06.697 * DB loaded from disk: 0.002 seconds
cache_1  | 1:M 20 Aug 06:03:06.697 * Ready to accept connections
db_1     | 2019-08-20  6:03:07 0 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!
db_1     | 2019-08-20  6:03:07 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
ctfd_1   | standard_init_linux.go:211: exec user process caused "no such file or directory"
db_1     | 2019-08-20  6:03:08 0 [ERROR] Plugin 'InnoDB' init function returned error.
db_1     | 2019-08-20  6:03:08 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1     | 2019-08-20  6:03:08 0 [ERROR] Unknown/unsupported storage engine: InnoDB
db_1     | 2019-08-20  6:03:08 0 [ERROR] Aborting
db_1     |
db_1     | Installation of system tables failed!  Examine the logs in
db_1     | /var/lib/mysql/ for more information.
db_1     |
db_1     | The problem could be conflicting information in an external
db_1     | my.cnf files. You can ignore these by doing:
db_1     |
db_1     |     shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf
db_1     |
db_1     | You can also try to start the mysqld daemon with:
db_1     |
db_1     |     shell> /usr/sbin/mysqld --skip-grant-tables --general-log &
db_1     |
db_1     | and use the command line tool /usr/bin/mysql
db_1     | to connect to the mysql database and look at the grant tables:
db_1     |
db_1     |     shell> /usr/bin/mysql -u root mysql
db_1     |     mysql> show tables;
db_1     |
db_1     | Try 'mysqld --help' if you have problems with paths.  Using
db_1     | --general-log gives you a log in /var/lib/mysql/ that may be helpful.
db_1     |
db_1     | The latest information about mysql_install_db is available at
db_1     | https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
db_1     | You can find the latest source at https://downloads.mariadb.org and
db_1     | the maria-discuss email list at https://launchpad.net/~maria-discuss
db_1     |
db_1     | Please check all of the above before submitting a bug report
db_1     | at http://mariadb.org/jira
db_1     |
db_1     | Initializing database
db_1     | 2019-08-20  6:03:10 0 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!
db_1     | 2019-08-20  6:03:10 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
ctfd_ctfd_1 exited with code 1
db_1     | 2019-08-20  6:03:11 0 [ERROR] Plugin 'InnoDB' init function returned error.
db_1     | 2019-08-20  6:03:11 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1     | 2019-08-20  6:03:11 0 [ERROR] Unknown/unsupported storage engine: InnoDB
db_1     | 2019-08-20  6:03:11 0 [ERROR] Aborting
db_1     |
db_1     | Installation of system tables failed!  Examine the logs in
db_1     | /var/lib/mysql/ for more information.
db_1     |
db_1     | The problem could be conflicting information in an external
db_1     | my.cnf files. You can ignore these by doing:
db_1     |
db_1     |     shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf
db_1     |
db_1     | You can also try to start the mysqld daemon with:
db_1     |
db_1     |     shell> /usr/sbin/mysqld --skip-grant-tables --general-log &
db_1     |
db_1     | and use the command line tool /usr/bin/mysql
db_1     | to connect to the mysql database and look at the grant tables:
db_1     |
db_1     |     shell> /usr/bin/mysql -u root mysql
db_1     |     mysql> show tables;
db_1     |
db_1     | Try 'mysqld --help' if you have problems with paths.  Using
db_1     | --general-log gives you a log in /var/lib/mysql/ that may be helpful.
db_1     |
db_1     | The latest information about mysql_install_db is available at
db_1     | https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
db_1     | You can find the latest source at https://downloads.mariadb.org and
db_1     | the maria-discuss email list at https://launchpad.net/~maria-discuss
db_1     |
db_1     | Please check all of the above before submitting a bug report
db_1     | at http://mariadb.org/jira
db_1     |
ctfd_db_1 exited with code 1
ctfd_ctfd_1 exited with code 1
ctfd_db_1 exited with code 1
Exception in thread Thread-10:
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\requests\models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localnpipe/v1.22/containers/390a4adc24b25055a7fbac05925b375dae6f515b459506544f2dc120693c964b/attach?logs=0&stdout=1&stderr=1&stream=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose\cli\log_printer.py", line 233, in watch_events
  File "compose\container.py", line 215, in attach_log_stream
  File "compose\container.py", line 307, in attach
  File "site-packages\docker\utils\decorators.py", line 19, in wrapped
  File "site-packages\docker\api\container.py", line 61, in attach
  File "site-packages\docker\api\client.py", line 400, in _read_from_socket
  File "site-packages\docker\api\client.py", line 311, in _get_raw_response_socket
  File "site-packages\docker\api\client.py", line 263, in _raise_for_status
  File "site-packages\docker\errors.py", line 19, in create_api_error_from_http_exception
  File "site-packages\requests\models.py", line 880, in json
  File "site-packages\requests\models.py", line 828, in content
  File "site-packages\requests\models.py", line 750, in generate
  File "site-packages\urllib3\response.py", line 496, in stream
  File "site-packages\urllib3\response.py", line 444, in read
  File "http\client.py", line 449, in read
  File "http\client.py", line 493, in readinto
  File "site-packages\docker\transport\npipesocket.py", line 209, in readinto
  File "site-packages\docker\transport\npipesocket.py", line 20, in wrapped
RuntimeError: Can not reuse socket after connection was closed.

ctfd_ctfd_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping ctfd_ctfd_1  ... done                                                                                          Stopping ctfd_db_1    ... done                                                                                          Stopping ctfd_cache_1 ... done 

```

**Comment by ColdHeat** [comment]
This seems like an issue specific to you installation. Not sure what's wrong. Can you reproduce on a Linux OS like Ubuntu?
