### ISSUE TITLE
CONNECT privilege Error

### ISSUE THREAD

**Issue by itechyboy** [CTFd/CTFd#1127]
**Environment**:
  - CTFd Version/Commit: 2.1.5
  - Operating System: Linux
  - Web Browser and Version: Mozilla Firefox for Ubuntu - 69.0.1

**What happened?**
Issue while deploying in heroku platform. I think it has problem with connection to the postgres database. I added ```Procfile``` with ```web: python wsgi.py runserver 0.0.0.0:4000```.
I also created pipenv because it needs psycopg2 package results in Pipfile & Pipfile.lock

**What did you expect to happen?**
I would expect you to modify for postgres connectivity for heroku. 

**Any associated stack traces or error logs**
```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    app = create_app()
  File "/app/CTFd/__init__.py", line 137, in create_app
    url = create_database()
  File "/app/CTFd/utils/migrations/__init__.py", line 25, in create_database
    if not database_exists_util(url):
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 481, in database_exists
    return bool(get_scalar_result(engine, text))
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 455, in get_scalar_result
    result_proxy = engine.execute(sql)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2165, in execute
    connection = self._contextual_connect(close_with_result=True)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2226, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2266, in _wrap_pool_connect
    e, dialect, self
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/app/.heroku/python/lib/python2.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.

(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by ColdHeat** [comment]
Postgres isn't well supported anymore and Heroku support isn't something CTFd claims. This doesn't seem really related to CTFd overall.

**Comment by 1UC1F3R616** [comment]
@itechyboy were u able to host it on heroku. help please

**Comment by bayuaz** [comment]
I have the same problem. So that means CTFd can't be deployed in Heroku right?

**Comment by 1UC1F3R616** [comment]
@bayuaz yes
