### ISSUE TITLE
Two errors occurred while executing the docker-compose

### ISSUE THREAD

**Issue by DrRem** [CTFd/CTFd#1162]
Two errors occurred while executing the docker-compose:
os: ubuntu-18.04.3-live-server-amd64
1.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

2.
ERROR: for ctfd_ctfd_1  a bytes-like object is required, not 'str'

ERROR: for ctfd  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.22/containers/17918b9e06819d9f78ce41e22c3a19e7d1b846f2a3999df32f9636dd7effce41/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 400 Client Error: Bad Request ("b'OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \\"/opt/CTFd/docker-entrypoint.sh\\": permission denied": unknown'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1106, in up
  File "compose/cli/main.py", line 1102, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 546, in execute_convergence_plan
  File "compose/service.py", line 467, in _execute_convergence_create
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 465, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[2611] Failed to execute script docker-compose

How to deal with it?

**Comment by ColdHeat** [comment]
Python 3 will be the main Docker image in 2.2.0. 

This second error looks like an issue with your Docker installation. The Dockerfile in master explicitly has `RUN chmod +x /opt/CTFd/docker-entrypoint.sh`

**Comment by aliabdelmalek00** [comment]
@ColdHeat 
this solution doesn't work
