### ISSUE TITLE
Abnormal shutdown causes ctfd to fail to start.  Urgent!

### ISSUE THREAD

**Issue by Gu-f** [CTFd/CTFd#1168]
**Environment**:

  - CTFd Version/Commit:V2.1.4
  - Operating System:ubuntu16.04

**What happened?**
My server shuts down due to an unexpected power outage，The service fails to start when I turn it on again.
**What did you expect to happen?**
How can I fix it?

**How to reproduce your issue**
This may happen if the server is directly powered off.

**Any associated stack traces or error logs**
Appears after executing 'python serve.py'

No handlers could be found for logger "flask_caching"
 * Loaded module, <module 'CTFd.plugins.challenges' from '/root/ctfd_platform/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/root/ctfd_platform/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/root/ctfd_platform/CTFd/CTFd/plugins/flags/__init__.pyc'>
 * Serving Flask app "CTFd" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:4000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/root/ctfd_platform/CTFd/serve.py", line 8, in <module>
    app = create_app()
  File "/root/ctfd_platform/CTFd/CTFd/__init__.py", line 186, in create_app
    version = utils.get_config("ctf_version")
  File "/root/ctfd_platform/CTFd/CTFd/utils/__init__.py", line 43, in get_config
    value = _get_config(key)
  File "/usr/local/lib/python2.7/dist-packages/flask_caching/__init__.py", line 671, in decorated_function
    f, *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/flask_caching/__init__.py", line 496, in make_cache_key
    f, args=args, timeout=_timeout, forced_update=forced_update
  File "/usr/local/lib/python2.7/dist-packages/flask_caching/__init__.py", line 461, in _memoize_version
    version_data_list = list(self.cache.get_many(*fetch_keys))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/contrib/cache.py", line 150, in get_many
    return [self.get(k) for k in keys]
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/contrib/cache.py", line 807, in get
    pickle_time = pickle.load(f)
EOFError

**Comment by ColdHeat** [comment]
The debug server is not a recommended way to deploy CTFd. Please see the documentation for better deployment options. http://docs.ctfd.io/en/latest/deployment.html

Secondly, power failures are not something CTFd really needs to be concerned with. It looks like the cache is having some issues retrieving data (probably b/c of the power failure). You should try to clear the cache by deleting the `.data` folder.
