### ISSUE TITLE
Trying to import a database from master on 2.2.0-dev crashes

### ISSUE THREAD

**Issue by krzys-h** [CTFd/CTFd#1187]
I tried to import the database exported from current `master` (97f5dcaf8c408a68ef0062d410b6c1599976688f) to `2.2.0-dev` (d46d1c7da64477da3e8b4e8541599229ac7a4776) to try out #1172 using the builtin import/export function, but the import crashed.

Seems to happen after 03235fe77263d24cd7d836bb8105b7d9af075724 (this is the commit that added the migration that fails during import), but the culprit is probably somewhere in the import code

**Environment**:

  - CTFd Version/Commit: 97f5dcaf8c408a68ef0062d410b6c1599976688f -> d46d1c7da64477da3e8b4e8541599229ac7a4776
  - Operating System: Ubuntu 19.04
  - Web Browser and Version: not relevant to the issue

**What happened?**

The import crashed

**What did you expect to happen?**

The import to work

**How to reproduce your issue**

```
git checkout master
rm -rf .data CTFd/ctfd.db
python manage.py db upgrade
python serve.py
# Set up CTF with some test data
python export.py export.zip
git checkout 2.2.0-dev
rm -rf .data CTFd/ctfd.db
python manage.py db upgrade
python serve.py
python import.py export.zip
```

**Any associated stack traces or error logs**

```
 * Loaded module, <module 'CTFd.plugins.challenges' from '/home/krzys_h/Pulpit/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/home/krzys_h/Pulpit/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/home/krzys_h/Pulpit/CTFd/CTFd/plugins/flags/__init__.pyc'>
Failed to disable foreign key checks. Continuing.
Traceback (most recent call last):
  File "import.py", line 11, in <module>
    import_ctf(sys.argv[1])
  File "/home/krzys_h/Pulpit/CTFd/CTFd/utils/exports/__init__.py", line 316, in import_ctf
    upgrade(revision="head")
  File "/usr/local/lib/python2.7/dist-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 89, in <module>
    run_migrations_online()
  File "migrations/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/home/krzys_h/Pulpit/CTFd/migrations/versions/080d29b15cd3_add_tokens_table.py", line 29, in upgrade
    sa.UniqueConstraint('value')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python2.7/dist-packages/alembic/operations/ops.py", line 1120, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python2.7/dist-packages/alembic/operations/base.py", line 319, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python2.7/dist-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 194, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table tokens already exists
[SQL: 
CREATE TABLE tokens (
	id INTEGER NOT NULL, 
	type VARCHAR(32), 
	user_id INTEGER, 
	created DATETIME, 
	expiration DATETIME, 
	value VARCHAR(128), 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	UNIQUE (value)
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by ColdHeat** [comment]
Thanks for reporting this. This appears to likely be specific to sqlite because of how poorly migrations are supported there.

**Comment by ColdHeat** [comment]
Hi can you pull 762b0596c6ac4be156891d8eaa040f940400e8f5 and confirm it fixes the issue?

**Comment by krzys-h** [comment]
The fix does seem to work... but

The error is NOT specific to sqlite only. I also tried it on mysql under Docker using the docker-compose.yml provided in the repo and it failed with the same error:
```
Traceback (most recent call last):
  File "import.py", line 11, in <module>
    import_ctf(sys.argv[1])
  File "/opt/CTFd/CTFd/utils/exports/__init__.py", line 316, in import_ctf
    upgrade(revision="head")
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 89, in <module>
    run_migrations_online()
  File "migrations/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/opt/CTFd/migrations/versions/080d29b15cd3_add_tokens_table.py", line 29, in upgrade
    sa.UniqueConstraint('value')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/ops.py", line 1250, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 252, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1044, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1050, "Table 'tokens' already exists")
[SQL: 
CREATE TABLE tokens (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	type VARCHAR(32), 
	user_id INTEGER, 
	created DATETIME, 
	expiration DATETIME, 
	value VARCHAR(128), 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	UNIQUE (value)
)

]
(Background on this error at: http://sqlalche.me/e/2j85)
```

After quickly looking through the import code, I think the problem is here:
https://github.com/CTFd/CTFd/blob/d46d1c7da64477da3e8b4e8541599229ac7a4776/CTFd/utils/exports/__init__.py#L214-L221
It seems that `create_all()` internally does the equivalent of `upgrade(revision="head")`, causing the database to upgrade before the import instead of after. And, since `stamp_latest_revision()` is not called, the second call to upgrade fails because the revision stamp doesn't match what's actually in the database. Removing this call seems to fix the issue as well (but I guess it may break some plugins)
