### ISSUE TITLE
通过gunicorn 20.0.4 部署出现错误

### ISSUE THREAD

**Issue by eonun** [CTFd/CTFd#1257]
```bash
[2020-02-21 15:17:13 +0800] [17336] [INFO] Starting gunicorn 20.0.4
[2020-02-21 15:17:13 +0800] [17336] [INFO] Listening at: http://0.0.0.0:8000 (17336)
[2020-02-21 15:17:13 +0800] [17336] [INFO] Using worker: sync
[2020-02-21 15:17:13 +0800] [17339] [INFO] Booting worker with pid: 17339
[2020-02-21 15:17:13 +0800] [17339] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/CTFd/CTFd/__init__.py", line 5, in <module>
    from flask import Flask, Request
ModuleNotFoundError: No module named 'flask'
[2020-02-21 15:17:13 +0800] [17339] [INFO] Worker exiting (pid: 17339)
[2020-02-21 15:17:13 +0800] [17336] [INFO] Shutting down: Master
[2020-02-21 15:17:13 +0800] [17336] [INFO] Reason: Worker failed to boot.
```

安装`gunicorn 20.0.4` 运行`gunicorn --bind 0.0.0.0:8000 -w 4 "CTFd:create_app()"`部署出现该错误
换成`gunicorn 19.10.0`后能正常部署

`gunicorn 20.x`以后使用的是python3了，所以可能是出现的不兼容，建议尽快升兼容版本

**Comment by ColdHeat** [comment]
CTFd is pinned to gunicorn==19.9.0. Can you root cause what the issue is here? I'm assuming it's more complicated than installing the flask dependency?

**Comment by ColdHeat** [comment]
CTFd v3 uses gunicorn 20.0.4. Not sure what the original issues is here though.

**Comment by osintcheck** [comment]
i run into the same error
