### ISSUE TITLE
vagrant up fails due to newer version of setuptools and banal

### ISSUE THREAD

**Issue by tommychinjr** [CTFd/CTFd#1345]
**Environment**:

  - CTFd Version/Commit: 05e5730c54355a3056f82f7ac38a864af5270ffd
  - Operating System: Ubuntu 19.10 x64
  - Web Browser and Version: Firefox 75.0 (64-bit)

**What happened?**
`vagrant up` fails to launch flask app due to python library dependency

**What did you expect to happen?**
vagrant to stage ctfd

**How to reproduce your issue**
vagrant up

**Any associated stack traces or error logs**
python serve.py
```
Traceback (most recent call last):
  File "serve.py", line 1, in <module>
    from CTFd import create_app
  File "/vagrant/CTFd/__init__.py", line 7, in <module>
    from flask import Flask, Request
ImportError: No module named flask
```
pip install -r requirements.txt
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 346, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: zipp>=0.5 .dist-info directory not found
```

**Comment by ColdHeat** [comment]
I ran into this recently and I think banal and normality need to be removed b/c they're originally there b/c of poor dependency management on dataset's part. Ultimately I think dataset/datafreeze needs to be removed entirely and brought in-house. 

https://github.com/pudo/banal/issues/5

**Comment by ColdHeat** [comment]
These dependencies were removed from requirements.txt so this should be resolved.
