### ISSUE TITLE
Constraint error when reset Challenges

### ISSUE THREAD

**Issue by erseco** [CTFd/CTFd#1386]
**Environment**:

  - CTFd Version/Commit: `master`
  - Operating System: `Docker`
  - Web Browser and Version: Chrome

**What happened?**

A 500 error caused for a SQL constraint: 
```
pymysql.err.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`ctfd`.`dynamic_challenge`, CONSTRAINT `dynamic_challenge_ibfk_1` FOREIGN KEY (`id`) REFERENCES `challenges` (`id`))')
```

**What did you expect to happen?**

Correct delete of Challenges

**How to reproduce your issue**

Add a `DynamicChallenge` and try to reset them in the `admin/reset` page

**Any associated stack traces or error logs**
```
ctfd_1   | 172.20.0.1 - - [06/May/2020:07:40:02 +0000] "GET /themes/admin/static/js/pages/reset.min.js?d=6ae26951 HTTP/1.1" 200 0 "http://localhost:8000/admin/reset" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
ctfd_1   | [2020-05-06 07:40:13,226] ERROR in app: Exception on /admin/reset [POST]
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
ctfd_1   |     cursor, statement, parameters, context
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
ctfd_1   |     cursor.execute(statement, parameters)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
ctfd_1   |     result = self._query(query)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
ctfd_1   |     conn.query(q)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
ctfd_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
ctfd_1   |     result.read()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
ctfd_1   |     first_packet = self.connection._read_packet()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
ctfd_1   |     packet.check_error()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
ctfd_1   |     err.raise_mysql_exception(self._data)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
ctfd_1   |     raise errorclass(errno, errval)
ctfd_1   | pymysql.err.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`ctfd`.`dynamic_challenge`, CONSTRAINT `dynamic_challenge_ibfk_1` FOREIGN KEY (`id`) REFERENCES `challenges` (`id`))')
ctfd_1   |
ctfd_1   | The above exception was the direct cause of the following exception:
ctfd_1   |
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
ctfd_1   |     response = self.full_dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
ctfd_1   |     rv = self.handle_user_exception(e)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 600, in error_router
ctfd_1   |     return original_handler(e)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
ctfd_1   |     reraise(exc_type, exc_value, tb)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
ctfd_1   |     raise value
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
ctfd_1   |     rv = self.dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
ctfd_1   |     return self.view_functions[rule.endpoint](**req.view_args)
ctfd_1   |   File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 110, in admins_only_wrapper
ctfd_1   |     return f(*args, **kwargs)
ctfd_1   |   File "/opt/CTFd/CTFd/admin/__init__.py", line 205, in reset
ctfd_1   |     Challenges.query.delete()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3752, in delete
ctfd_1   |     delete_op.exec_()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1693, in exec_
ctfd_1   |     self._do_exec()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1921, in _do_exec
ctfd_1   |     self._execute_stmt(delete_stmt)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1698, in _execute_stmt
ctfd_1   |     self.result = self.query._execute_crud(stmt, self.mapper)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3400, in _execute_crud
ctfd_1   |     return conn.execute(stmt, self._params)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
ctfd_1   |     return meth(self, multiparams, params)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
ctfd_1   |     return connection._execute_clauseelement(self, multiparams, params)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
ctfd_1   |     distilled_params,
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
ctfd_1   |     e, statement, parameters, cursor, context
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
ctfd_1   |     util.raise_from_cause(sqlalchemy_exception, exc_info)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
ctfd_1   |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
ctfd_1   |     raise value.with_traceback(tb)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
ctfd_1   |     cursor, statement, parameters, context
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
ctfd_1   |     cursor.execute(statement, parameters)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
ctfd_1   |     result = self._query(query)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
ctfd_1   |     conn.query(q)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
ctfd_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
ctfd_1   |     result.read()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
ctfd_1   |     first_packet = self.connection._read_packet()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
ctfd_1   |     packet.check_error()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
ctfd_1   |     err.raise_mysql_exception(self._data)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
ctfd_1   |     raise errorclass(errno, errval)
ctfd_1   | sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`ctfd`.`dynamic_challenge`, CONSTRAINT `dynamic_challenge_ibfk_1` FOREIGN KEY (`id`) REFERENCES `challenges` (`id`))')
ctfd_1   | [SQL: DELETE FROM challenges]
ctfd_1   | (Background on this error at: http://sqlalche.me/e/gkpj)
ctfd_1   | 172.20.0.1 - - [06/May/2020:07:40:13 +0000] "POST /admin/reset HTTP/1.1" 500 4715 "http://localhost:8000/admin/reset" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
```

**Comment by ColdHeat** [comment]
Hmm thanks for flagging this. I had thought there were deletion constraints on this. This raises a bunch of other problems though so this will take some time to fix up.
