### ISSUE TITLE
Importing in PGSQL DB is failing on 2.4.0

### ISSUE THREAD

**Issue by RaitoBezarius** [CTFd/CTFd#1392]
**Environment**:

  - CTFd Version/Commit: 2.4.0 (tagged)
  - Operating System: `Linux 4.19.66-gentoo #4 SMP Mon Aug 19 18:40:12 BST 2019 x86_64 Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz GenuineIntel GNU
/Linux`
  - Web Browser and Version: Not relevant.

**What happened?**

I have an exported ZIP from a MySQL valid production DB, I wanted to move to PostgreSQL, because MySQL is giving us a lot of disconnections errors (we tried to change the recycle, etc. But no luck, I'm no specialist of this DBMS, so I prefer my battle-tested PGSQL).

So when I try a `./import.py export.zip`, we get a foreign key violation and it fails.

**What did you expect to happen?**
The DB is imported.

**How to reproduce your issue**

Export, import.

**Any associated stack traces or error logs**
```
 * Loaded module, <module 'CTFd.plugins.challenges' from '/home/ctfd/CTFd/CTFd/plugins/challenges/__init__.py'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/home/ctfd/CTFd/CTFd/plugins/dynamic_challenges/__init__.py'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/home/ctfd/CTFd/CTFd/plugins/flags/__init__.py'>
Failed to disable foreign key checks. Continuing.
Allowing error during app.db.create_all() due to Postgres
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "teams" violates foreign key constraint "team_captain_id"
DETAIL:  Key (captain_id)=(4) is not present in table "users".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "import.py", line 11, in <module>
    import_ctf(sys.argv[1])
  File "/home/ctfd/CTFd/CTFd/utils/exports/__init__.py", line 241, in import_ctf
    table.insert(entry)
  File "/home/ctfd/.local/lib64/python3.6/site-packages/dataset/table.py", line 80, in insert
    res = self.db.executable.execute(self.table.insert(row))
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "teams" violates foreign key con
straint "team_captain_id"
DETAIL:  Key (captain_id)=(4) is not present in table "users".

[SQL: INSERT INTO teams (id, oauth_id, name, email, password, secret, website, affiliation, country, bracket, hidden, banned, c
reated, captain_id) VALUES (%(id)s, %(oauth_id)s, %(name)s, %(email)s, %(password)s, %(secret)s, %(website)s, %(affiliation)s, 
%(country)s, %(bracket)s, %(hidden)s, %(banned)s, %(created)s, %(captain_id)s)]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by RaitoBezarius** [comment]
Nevermind, it seems like CTFd user must be superuser to run the import. It would be nice to add it to the documentation.

**Comment by ColdHeat** [comment]
Postgres is no longer a primarily supported database. The documentation recommends MySQL and CTFd is tested against Postgres but will likely be deprecated in the next major version. I don't think it's necessary to document behavior that's going to be deprecated and isn't really recommended.

**Comment by RaitoBezarius** [comment]
With MySQL, we encountered many disconnections on 2.4.0, hang outs,
cache issues and a lot of stuff. :/

I guess I'll open something on this.
