### ISSUE TITLE
Many disconnections and cache issues on 2.4.0 with MySQL

### ISSUE THREAD

**Issue by RaitoBezarius** [CTFd/CTFd#1395]
**Environment**:

- CTFd Version/Commit: 2.4.0 (tagged)
- Operating System: `Linux 4.19.66-gentoo #4 SMP Mon Aug 19 18:40:12 BST 2019 x86_64 Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz GenuineIntel GNU /Linux`
- Web Browser and Version: Confirmed over Firefox 76 / Chromium 81

**What happened?**

Many disconnections & caches issues impairing the usability of the website.

- Hints are not showed sometimes.
- Challenges don't appear when visibility hidden → visible.
- Scoreboard is never refreshed until Ctrl + R (not related to MySQL, we confirmed this on PGSQL).
- Infinite login loops when we click on challenges/scoreboard.

**What did you expect to happen?**

To not have random disconnects, cache issues, users are not able to see some challenges, they're forced to clear their cache, go into private navigation, we, admins, are forced to Ctrl + R everywhere to see updated stuff.

Redis is being used, we see keys in the cache.

**How to reproduce your issue**

We just cloned CTFd on 2.4.0, set a MySQL, run the setup, add Redis, that's all.
We used uwsgi, gunicorn, with async event, playing with the threads/workers amount, modifying the recycle pool timer, nothing worked.

**Any associated stack traces or error logs**

```
File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib64/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/lib64/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: SELECT config.id AS config_id, config.`key` AS config_key, config.value AS config_value 
FROM config 
WHERE config.`key` = %(key_1)s 
 LIMIT %(param_1)s]
[parameters: {'key_1': 'setup', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1171, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 457, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/lib64/python3.6/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/usr/lib64/python3.6/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask_restx/api.py", line 600, in error_router
    return original_handler(e)
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask/app.py", line 1878, in handle_exception
    server_error = handler(server_error)
  File "/home/ctfd/CTFd/CTFd/errors.py", line 16, in general_error
    return render_template("errors/500.html"), 500
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib64/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib64/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ctfd/CTFd/CTFd/__init__.py", line 85, in _load_template
    theme = str(utils.get_config("ctf_theme"))
  File "/home/ctfd/CTFd/CTFd/utils/__init__.py", line 44, in get_config
    value = _get_config(key)
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask_caching/__init__.py", line 686, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/ctfd/CTFd/CTFd/utils/__init__.py", line 26, in _get_config
    config = Configs.query.filter_by(key=key).first()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1176, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1171, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 457, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
[SQL: SELECT config.id AS config_id, config.`key` AS config_key, config.value AS config_value 
FROM config 
WHERE config.`key` = %(key_1)s 
 LIMIT %(param_1)s]
[parameters: [immutabledict({})]]
[2020-05-09 17:30:20,137] ERROR in app: Exception on /events [GET]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib64/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/lib64/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask_restx/api.py", line 600, in error_router
    return original_handler(e)
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/ctfd/CTFd/CTFd/utils/initialization/__init__.py", line 213, in banned
    user = get_current_user_attrs()
  File "/home/ctfd/CTFd/CTFd/utils/user/__init__.py", line 24, in get_current_user_attrs
    return get_user_attrs(user_id=session["id"])
  File "/home/ctfd/.local/lib64/python3.6/site-packages/flask_caching/__init__.py", line 686, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/ctfd/CTFd/CTFd/utils/user/__init__.py", line 31, in get_user_attrs
    user = Users.query.filter_by(id=user_id).first()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib64/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/lib64/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: SELECT users.id AS users_id, users.oauth_id AS users_oauth_id, users.name AS users_name, users.password AS users_password, users.email AS users_email, users.type AS users_type, users.secret AS users_secret, users.website AS users_website, users.affiliation AS users_affiliation, users.country AS users_country, users.bracket AS users_bracket, users.hidden AS users_hidden, users.banned AS users_banned, users.verified AS users_verified, users.team_id AS users_team_id, users.created AS users_created 
FROM users 
WHERE users.id = %(id_1)s 
 LIMIT %(param_1)s]
[parameters: {'id_1': 14, 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/e3q8)
[2020-05-09 17:30:20 +0100] [28191] [ERROR] Error handling request /events
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib64/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/lib64/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/lib64/python3.6/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
```

**Comment by ColdHeat** [comment]
Without a reproducible issue, there's no way to debug this. Why is CTFd losing a connection to MySQL in the middle of a query? That to me makes it seem indicative of an issue in your infrastructure versus an issue in CTFd.

**Comment by ColdHeat** [comment]
I just tried this out myself with `docker-compose` and creating a challenge + hint as admin and then viewing a challenge + hint as a non-admin worked fine.

You'll need to provide a lot more context here.

**Comment by RaitoBezarius** [comment]
We don't use docker-compose, we'll try to check if there are precise logs on this.
