### ISSUE TITLE
Error while installing CTFd

### ISSUE THREAD

**Issue by PunitTailor55** [CTFd/CTFd#1421]
**Environment**:

  - CTFd Version/Commit:
  - Operating System: AWS EC2 instance Ubuntu 18.04
  - Web Browser and Version: Chrome

**What happened?**
I have downloaded from git and followed the given steps.
**What did you expect to happen?**
Run the given application
**How to reproduce your issue**

**Any associated stack traces or error logs**
```
Traceback (most recent call last):
  File "serve.py", line 11, in <module>
    app = create_app()
  File "/home/ubuntu/RSG/CTFd/CTFd/__init__.py", line 258, in create_app
    from CTFd.admin import admin
  File "/home/ubuntu/RSG/CTFd/CTFd/admin/__init__.py", line 36, in <module>
    from CTFd.utils.exports import export_ctf as export_ctf_util
  File "/home/ubuntu/RSG/CTFd/CTFd/utils/exports/__init__.py", line 8, in <module>
    import dataset
ImportError: No module named dataset


```

**Comment by ColdHeat** [comment]
Did you follow the install instructions? You are missing dependencies (i.e. run the `pip` command)
https://github.com/CTFd/CTFd#install

**Comment by PunitTailor55** [comment]
I have followed the same steps and configure database as well.

**Comment by PunitTailor55** [comment]
New Error!

```
Traceback (most recent call last):
  File "serve.py", line 13, in <module>
    app = create_app()
  File "/home/ubuntu/ctfd/CTFd/CTFd/__init__.py", line 225, in create_app
    from CTFd.admin import admin
  File "/home/ubuntu/ctfd/CTFd/CTFd/admin/__init__.py", line 33, in <module>
    from CTFd.utils.exports import export_ctf as export_ctf_util
  File "/home/ubuntu/ctfd/CTFd/CTFd/utils/exports/__init__.py", line 8, in <module>
    import datafreeze
  File "/home/ubuntu/.local/lib/python2.7/site-packages/datafreeze/__init__.py", line 1, in <module>
    from datafreeze.app import freeze
  File "/home/ubuntu/.local/lib/python2.7/site-packages/datafreeze/app.py", line 8, in <module>
    from datafreeze.format import get_serializer
  File "/home/ubuntu/.local/lib/python2.7/site-packages/datafreeze/format/__init__.py", line 1, in <module>
    from datafreeze.format.fjson import JSONSerializer
  File "/home/ubuntu/.local/lib/python2.7/site-packages/datafreeze/format/fjson.py", line 8, in <module>
    from datafreeze.format.common import Serializer
  File "/home/ubuntu/.local/lib/python2.7/site-packages/datafreeze/format/common.py", line 7, in <module>
    from normality import slugify
  File "/home/ubuntu/.local/lib/python2.7/site-packages/normality/__init__.py", line 7, in <module>
    from normality.paths import safe_filename  # noqa
  File "/home/ubuntu/.local/lib/python2.7/site-packages/normality/paths.py", line 2, in <module>
    from banal import decode_path
  File "/home/ubuntu/.local/lib/python2.7/site-packages/banal/__init__.py", line 1, in <module>
    from banal.lists import is_sequence, is_listish
  File "/home/ubuntu/.local/lib/python2.7/site-packages/banal/lists.py", line 5
    def is_sequence(obj: Any) -> bool:
```

**Comment by ColdHeat** [comment]
Are you running the most recent copy of the code?

**Comment by PunitTailor55** [comment]
Yes!

**Comment by fjh1997** [comment]
Pin banal==0.4.2 in requirements.txt fix this
