### ISSUE TITLE
Reset Password Email server

### ISSUE THREAD

**Issue by pc84560895** [CTFd/CTFd#149]
```
[2016-09-04 01:42:44,183] ERROR in app: Exception on /reset_password [POST]
Traceback (most recent call last):
  File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./CTFd/auth.py", line 74, in reset_password
    sendmail(email, text)
  File "./CTFd/utils.py", line 326, in sendmail
    mg_base_url + '/messages',
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

When I tried to reset my password after i set up my email server, it gave me this error.

**Comment by ColdHeat** [comment]
Are you running from master? 

I believe this issue is fixed in master.

**Comment by pc84560895** [comment]
It works after updated. However, it can only work with TLS and not the SSL option. I set up my email server via zoho email. Thanks anyways for such a wonderful project!! <3

**Comment by ColdHeat** [comment]
Hmm. Perhaps there is an issue.

**Comment by pc84560895** [comment]
It throws me this exception 
SMTPServerDisconnected

**Comment by ColdHeat** [comment]
Some email providers have disabled SSL in favor of TLS. Perhaps you are using the wrong port or Zoho has disabled SSL?

**Comment by pc84560895** [comment]
They provide both SSL and TLS. I have used the correct port as well. It works when I use the TLS option instead.

**Comment by ColdHeat** [comment]
Think you can give me a stack trace?

**Comment by pc84560895** [comment]
File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/CTFd/CTFd/auth.py", line 74, in reset_password
sendmail(email, text)
File "/opt/CTFd/CTFd/utils.py", line 369, in sendmail
smtp = get_smtp(**data)
File "/opt/CTFd/CTFd/utils.py", line 329, in get_smtp
smtp = smtplib.SMTP(host, port)
File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
(code, msg) = self.connect(host, port)
File "/usr/lib/python2.7/smtplib.py", line 317, in connect
(code, msg) = self.getreply()
File "/usr/lib/python2.7/smtplib.py", line 368, in getreply
raise SMTPServerDisconnected("Connection unexpectedly closed")

**Comment by pc84560895** [comment]
I used nginx+uwsgi as my ctfd platform. but this time round it doesn't work for TLS as well.
However, if i run as flask on serve.py, TLS email service can work.

Traceback (most recent call last):
  File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ctfmain/.local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./CTFd/auth.py", line 74, in reset_password
    sendmail(email, text)
  File "./CTFd/utils.py", line 370, in sendmail
    msg = email.mime.text.MIMEText(text)

**Comment by pc84560895** [comment]
from email.mime.text import MIMEText
msg = email.mime.text.MIMEText(text) to MIMEText(text)
I changed the import statement and one line of the code and it works HAHA. IDK WHYYY

**Comment by ColdHeat** [comment]
This is a pretty old issue, and I believe it's been fixed because the code seems familiar. Feel free to re-open if it's still an issue.
