### ISSUE TITLE
[Bug] Incorrect POST request when submitting the flag for dynamic challenges

### ISSUE THREAD

**Issue by gmelodie** [CTFd/CTFd#1542]
**Environment**:
- Operating System: Linux
- Web Browser and Version: All I tested (Firefox, Safari, Explorer, etc.)

**What happened?**
An incorrect request was generated when trying to submit the flag for a dynamic challenge (standard challenges work fine). It seems to be lacking the `submission` field.

**What did you expect to happen?**
Flag to be correctly submitted.

**Any associated stack traces or error logs**
```
ERROR [CTFd] Exception on /api/v1/challenges/attempt [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/CTFd/CTFd/utils/decorators/visibility.py", line 56, in _check_challenge_visibility
    return f(*args, **kwargs)
  File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 23, in during_ctf_time_only_wrapper
    return f(*args, **kwargs)
  File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 72, in _require_verified_emails
    return f(*args, **kwargs)
  File "/opt/CTFd/CTFd/api/v1/challenges.py", line 562, in post
    status, message = chal_class.attempt(challenge, request)
  File "/opt/CTFd/CTFd/plugins/challenges/__init__.py", line 118, in attempt
    submission = data["submission"].strip()
KeyError: 'submission'
```

**Comment by ColdHeat** [comment]
Yes this is related to #1540.

**Comment by ColdHeat** [comment]
I merged the fix in. You can pull from master to update.
