### ISSUE TITLE
unable to insert into database

### ISSUE THREAD

**Issue by natcoso9955** [CTFd/CTFd#1592]
**Environment**: unraid docker

- CTFd Version/Commit: latest (3.0.0)
- Operating System: unraid
- Web Browser and Version: N/A

**What happened?**
when trying to patch the hash_crack_king plugin (https://github.com/Akm0d/CTFd_hash_crack_king) to work, it is trying to insert into the database (using local sqlite) and it is saying its read-only.
**What did you expect to happen?**
code to get inserted when called as part of plugin being called that needs to insert into the db.
**How to reproduce your issue**
download koth plugin and replace init file with [modified version](https://github.com/natcoso9955/unRAID-docker/raw/master/configs/CTFd/plugins/hash_crack_king/__init__.py)
**Any associated stack traces or error logs**
`Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
cursor, statement, parameters, context
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "manage.py", line 9, in <module>
app = create_app()
File "/opt/CTFd/CTFd/__init__.py", line 281, in create_app
init_plugins(app)
File "/opt/CTFd/CTFd/plugins/__init__.py", line 196, in init_plugins
module.load(app)
File "/opt/CTFd/CTFd/plugins/hash_crack_king/__init__.py", line 400, in load
app.db.create_all()
File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
self._execute_for_all_tables(app, bind, 'create_all')
File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
op(bind=self.get_engine(app, bind), **extra)
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4465, in create_all
ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2104, in _run_visitor
conn._run_visitor(visitorcallable, element, **kwargs)
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1663, in _run_visitor
visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 787, in visit_metadata
_is_metadata_operation=True,
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 832, in visit_table
include_foreign_key_constraints, # noqa
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
return connection._execute_ddl(self, multiparams, params)
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1082, in _execute_ddl
compiled,
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
e, statement, parameters, cursor, context
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
sqlalchemy_exception, with_traceback=exc_info[2], from_=e
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
raise exception
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
cursor, statement, parameters, context
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL:
CREATE TABLE hash_crack_king_challenge (
id INTEGER NOT NULL,
initial INTEGER,
hold INTEGER,
cycles INTEGER,
current_hash VARCHAR(80),
king INTEGER,
regex VARCHAR(160),
PRIMARY KEY (id),
FOREIGN KEY(id) REFERENCES challenges (id)
)`

**Comment by ColdHeat** [comment]
This isn't a CTFd issue and the issue tracker isn't a good place to get tech support.

**Comment by natcoso9955** [comment]
It's your Docker image that is saying the database is read-only. So it IS a CTFd issue.
