### ISSUE TITLE
Bug in freeze 

### ISSUE THREAD

**Issue by dakiro** [CTFd/CTFd#1635]
- CTFd version 3

Error 500 in scoreboard with freeze time enable

**Any associated stack traces or error logs** 

```
NameError: name 'unix_time_to_utc' is not defined
ERROR [CTFd] Exception on /scoreboard [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/CTFd/CTFd/utils/decorators/visibility.py", line 25, in _check_score_visibility
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py", line 436, in decorated_function
    rv = f(*args, **kwargs)
  File "/opt/CTFd/CTFd/plugins/CTFd-pwn-college-plugin/scoreboard.py", line 80, in scoreboard_listing
    category_standings = get_category_standings()
  File "/opt/CTFd/CTFd/plugins/CTFd-pwn-college-plugin/scoreboard.py", line 37, in get_category_standings
    scores = scores.filter(Solves.date < unix_time_to_utc(freeze))
NameError: name 'unix_time_to_utc' is not defined
```

**Comment by ColdHeat** [comment]
This looks like an issue in a plugin, not in core CTFd. Please raise this issue with the plugin maintainers.
