### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by sep3** [CTFd/CTFd#1642]
Hi, I got this error, while importing a challenge using the ctf-cli tool.

**Environment**:
- CTFd Version/Commit: 2.5.0
- Operating System: Ubuntu 20

**What happened?**
$ ctf challenge sync exe1

value: 600
type: dynamic
decay: 450
minimum: 100

$ docker compose-up
ctfd_1   | ERROR [CTFd] Exception on /api/v1/challenges/1 [PATCH]
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
ctfd_1   |     rv = self.dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
ctfd_1   |     return self.view_functions[rule.endpoint](**req.view_args)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 339, in wrapper
ctfd_1   |     resp = resource(*args, **kwargs)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
ctfd_1   |     return self.dispatch_request(*args, **kwargs)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
ctfd_1   |     resp = meth(*args, **kwargs)
ctfd_1   |   File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 110, in admins_only_wrapper
ctfd_1   |     return f(*args, **kwargs)
ctfd_1   |   File "/opt/CTFd/CTFd/api/v1/challenges.py", line 284, in patch
ctfd_1   |     challenge = challenge_class.update(challenge, request)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/dynamic_challenges/__init__.py", line 149, in update
ctfd_1   |     return DynamicValueChallenge.calculate_value(challenge)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/dynamic_challenges/__init__.py", line 72, in calculate_value
ctfd_1   |     ((challenge.minimum - challenge.initial) / (challenge.decay ** 2))
ctfd_1   | ZeroDivisionError: division by zero
ctfd_1   | 10.3.1.241 - - [10/Sep/2020:03:34:54 +0000] "PATCH /api/v1/challenges/1 HTTP/1.1" 500 37 "-" "python-requests/2.22.0"

**Comment by ColdHeat** [comment]
I think right now dynamic challenges aren't supported via ctfcli. It's an open issue that I haven't fixed just yet. See https://github.com/CTFd/ctfcli/pull/19.
