### ISSUE TITLE
No module named 'tenacity'

### ISSUE THREAD

**Issue by jensregel** [CTFd/CTFd#1665]
**Environment**:

- CTFd Version/Commit:

```
# git log -1
commit ed64b4871d43f21666bdf1e3de4c2b5fbd1b098a (HEAD -> master, tag: 3.1.1, origin/master, origin/HEAD)
```

- Operating System:

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

**What happened?**
After upgrading to 3.1.1, CTFd won't come up with `docker-compose up`. Module tenacity is not found but is already installed.

```
# pip show tenacity
Name: tenacity
Version: 6.2.0
Summary: Retry code until it succeeds
Home-page: https://github.com/jd/tenacity
Author: Julien Danjou
Author-email: julien@danjou.info
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: typing, monotonic, futures, six
```
```
# pip3 show tenacity
Name: tenacity
Version: 6.2.0
Summary: Retry code until it succeeds
Home-page: https://github.com/jd/tenacity
Author: Julien Danjou
Author-email: julien@danjou.info
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: six

```

**Any associated stack traces or error logs**

```
ctfd_1   | .db is ready
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "manage.py", line 5, in <module>
ctfd_1   |     from CTFd import create_app
ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 18, in <module>
ctfd_1   |     from CTFd.utils.initialization import (
ctfd_1   |   File "/opt/CTFd/CTFd/utils/initialization/__init__.py", line 24, in <module>
ctfd_1   |     from CTFd.utils.events import EventManager, RedisEventManager
ctfd_1   |   File "/opt/CTFd/CTFd/utils/events/__init__.py", line 6, in <module>
ctfd_1   |     from tenacity import retry, wait_exponential
ctfd_1   | ModuleNotFoundError: No module named 'tenacity'
```

**Comment by ColdHeat** [comment]
Perhaps try running `docker-compose --no-cache build` and then `docker-compose up` again?

**Comment by jensregel** [comment]
Thanks, after a successful `docker-compose build --no-cache` the module tenacity has been found, but there is now a another error.

```
db_1     | 2020-09-28  7:54:29 0 [Note] mysqld: ready for connections.
db_1     | Version: '10.4.12-MariaDB-1:10.4.12+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
db_1     | 2020-09-28  7:54:29 0 [Note] InnoDB: Buffer pool(s) load completed at 200928  7:54:29
ctfd_1   | [2020-09-28 07:55:04 +0000] [27] [INFO] Booting worker with pid: 27
ctfd_1   | /usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
ctfd_1   |   return f(*args, **kwds)
ctfd_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
ctfd_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ctfd_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
ctfd_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ctfd_1   | [2020-09-28 07:55:20 +0000] [29] [INFO] Booting worker with pid: 29
ctfd_1   | /usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
ctfd_1   |   return f(*args, **kwds)
ctfd_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
ctfd_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ctfd_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
ctfd_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```

**Comment by ColdHeat** [comment]
That sounds like the same issue as #1667. Try installing greenlet==0.4.16 (`pip install greenlet==0.4.16`).

Does CTFd work or does it fail to load completely? 

I'm going to close this out because the original issue is resolved.
