### ISSUE TITLE
Freeze versions for all Python requirements

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#1679]
Like in #1675 we should review all the dependencies to see if we can pin exactly what dependencies we want. Something like pip freeze.

**Comment by ColdHeat** [comment]
Running pip freeze in a fresh venv results in the following:

```
alembic==1.4.3
aniso8601==8.0.0
attrs==20.2.0
bcrypt==3.1.7
boto3==1.13.9
botocore==1.16.26
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
cmarkgfm==0.4.2
dataset==1.3.1
docutils==0.15.2
Flask==1.1.2
Flask-Caching==1.8.0
flask-marshmallow==0.10.1
Flask-Migrate==2.5.3
flask-restx==0.2.0
Flask-Script==2.0.6
Flask-SQLAlchemy==2.4.3
gevent==20.9.0
greenlet==0.4.17
gunicorn==20.0.4
html5lib==1.0.1
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
jmespath==0.10.0
jsonschema==3.2.0
lxml==4.5.1
Mako==1.1.3
MarkupSafe==1.1.1
marshmallow==2.20.2
marshmallow-sqlalchemy==0.17.0
maxminddb==1.5.4
passlib==1.7.2
pycparser==2.20
pydantic==1.5.1
PyMySQL==0.9.3
pyrsistent==0.17.3
python-dateutil==2.8.1
python-dotenv==0.13.0
python-editor==1.0.4
python-geoacumen==0.0.1
pytz==2020.1
redis==3.5.2
requests==2.23.0
s3transfer==0.3.3
six==1.15.0
SQLAlchemy==1.3.17
SQLAlchemy-Utils==0.36.6
tenacity==6.2.0
urllib3==1.25.10
webencodings==0.5.1
Werkzeug==1.0.1
WTForms==2.3.1
zope.event==4.5.0
zope.interface==5.1.2
```

**Comment by h3xstream** [comment]
Using these helped me fix a crash I had at startup.
```
zope.event==4.5.0
zope.interface==5.1.2
```
Error I had with unaligned version.
```
> python serve.py
 * Importing gevent and monkey patching. Use --disable-gevent to disable.
Traceback (most recent call last):
  File "serve.py", line 18, in <module>
    monkey.patch_all()
  File "C:\Python37-32\lib\site-packages\gevent\monkey.py", line 1210, in patch_all
    from gevent import events
  File "C:\Python37-32\lib\site-packages\gevent\events.py", line 67, in <module>
    from zope.interface import Interface
ModuleNotFoundError: No module named 'zope.interface'
```

Having fix versions will definitely helps. 👍

**Comment by ColdHeat** [comment]
https://github.com/jazzband/pip-tools seems to do a good job here. The installed deps appear to be mostly the same between the docker image and what I get on my Mac. The main differences appear to be based on Python version which isn't a huge concern but some care should be taken to see what Windows generates. 

For reference here is the docker command output:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
alembic==1.4.3            # via dataset, flask-migrate
aniso8601==8.0.0          # via flask-restx
attrs==20.3.0             # via jsonschema
bcrypt==3.1.7             # via -r requirements.in
boto3==1.13.9             # via -r requirements.in
botocore==1.16.26         # via boto3, s3transfer
certifi==2020.11.8        # via requests
cffi==1.14.3              # via bcrypt, cmarkgfm
chardet==3.0.4            # via requests
click==7.1.2              # via flask
cmarkgfm==0.4.2           # via -r requirements.in
dataset==1.3.1            # via -r requirements.in
docutils==0.15.2          # via botocore
flask-caching==1.8.0      # via -r requirements.in
flask-marshmallow==0.10.1  # via -r requirements.in
flask-migrate==2.5.3      # via -r requirements.in
flask-restx==0.2.0        # via -r requirements.in
flask-script==2.0.6       # via -r requirements.in
flask-sqlalchemy==2.4.3   # via -r requirements.in, flask-migrate
flask==1.1.2              # via -r requirements.in, flask-caching, flask-marshmallow, flask-migrate, flask-restx, flask-script, flask-sqlalchemy
gevent==20.9.0            # via -r requirements.in
greenlet==0.4.17          # via gevent
gunicorn==20.0.4          # via -r requirements.in
html5lib==1.0.1           # via -r requirements.in
idna==2.10                # via requests
importlib-metadata==2.0.0  # via jsonschema
itsdangerous==1.1.0       # via -r requirements.in, flask
jinja2==2.11.2            # via -r requirements.in, flask
jmespath==0.10.0          # via boto3, botocore
jsonschema==3.2.0         # via flask-restx
lxml==4.5.1               # via -r requirements.in
mako==1.1.3               # via alembic
markupsafe==1.1.1         # via jinja2, mako, wtforms
marshmallow-sqlalchemy==0.17.0  # via -r requirements.in
marshmallow==2.20.2       # via -r requirements.in, flask-marshmallow, marshmallow-sqlalchemy
maxminddb==1.5.4          # via -r requirements.in, python-geoacumen
passlib==1.7.2            # via -r requirements.in
pycparser==2.20           # via cffi
pydantic==1.5.1           # via -r requirements.in
pymysql==0.9.3            # via -r requirements.in
pyrsistent==0.17.3        # via jsonschema
python-dateutil==2.8.1    # via alembic, botocore
python-dotenv==0.13.0     # via -r requirements.in
python-editor==1.0.4      # via alembic
python-geoacumen==0.0.1   # via -r requirements.in
pytz==2020.4              # via flask-restx
redis==3.5.2              # via -r requirements.in
requests==2.23.0          # via -r requirements.in
s3transfer==0.3.3         # via boto3
six==1.15.0               # via bcrypt, flask-marshmallow, flask-restx, html5lib, jsonschema, python-dateutil, sqlalchemy-utils, tenacity
sqlalchemy-utils==0.36.6  # via -r requirements.in
sqlalchemy==1.3.17        # via -r requirements.in, alembic, dataset, flask-sqlalchemy, marshmallow-sqlalchemy, sqlalchemy-utils
tenacity==6.2.0           # via -r requirements.in
urllib3==1.25.11          # via botocore, requests
webencodings==0.5.1       # via html5lib
werkzeug==1.0.1           # via -r requirements.in, flask, flask-restx
wtforms==2.3.1            # via -r requirements.in
zipp==3.4.0               # via importlib-metadata
zope.event==4.5.0         # via gevent
zope.interface==5.2.0     # via gevent

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

**Comment by ColdHeat** [comment]
I didn't find major differences between version or environment that pip itself wouldn't resolve so I'm going to push up a fix for this soon.
