### ISSUE TITLE
PyBlueMonday refuses to work (CFFI Include Issues) on Raspbian/RPi

### ISSUE THREAD

**Issue by aussieklutz** [CTFd/CTFd#1854]
**Environment**:

- CTFd Version/Commit: 3.3.0
- Operating System: Raspbian
- Web Browser and Version: NA, Python Issue

**What happened?**
On attempting to launch via flask on Raspbian OS, the targeted version of PyBlueMonday fails to initialize due to a non-working ffi import of the bluemonday shared object.

**What did you expect to happen?**
Flask to load properly

**How to reproduce your issue**
On Raspbian, attempt to start flask, flask fails to start. 

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
Thanks for reporting this. I'll make ARM wheels for pybluemonday when I get the chance. In the meantime I would probably recommend using 3.2.1 or commenting out most of the code here: https://github.com/CTFd/CTFd/blob/master/CTFd/utils/security/sanitize.py and modifying the sanitize_html function to just return the html.

**Comment by ColdHeat** [comment]
Now that I'm digging into it, this issue kind of needs more details... Were you able to install pybluemonday at all?

**Comment by okuyanf61** [comment]
Yes I installed it.

**Comment by ColdHeat** [comment]
Can you try to pip install pybluemonday on your Pi? I believe it should work now since there are ARM wheels on PyPI now. 

Can also keep an eye on https://github.com/piwheels/packages/issues/197.

**Comment by cpsears** [comment]
I'm working on a Ubuntu 20.04 system (GNU/Linux 5.4.0-1047-azure x86_64). Azure VM. 

When I 'docker-compose up -d', the CTFd container failed and continually restarts.
```
$ docker ps
CONTAINER ID   IMAGE             COMMAND                  CREATED          STATUS                        PORTS                                                                      NAMES
b44210730b31   nginx:1.17        "nginx -g 'daemon of…"   28 seconds ago   Up 24 seconds                 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   ctfd_nginx_1
f54f50054e90   ctfd_ctfd         "/opt/CTFd/docker-en…"   30 seconds ago   Restarting (1) 1 second ago                                                                              ctfd_ctfd_1
e37cc477f6cf   redis:4           "docker-entrypoint.s…"   32 seconds ago   Up 29 seconds                                                                                            ctfd_cache_1
2f819cf3733e   mariadb:10.4.12   "docker-entrypoint.s…"   32 seconds ago   Up 29 seconds                                                                                            ctfd_db_1
```

Docker logs shows that this is an issue with pybluemonday. I have tried pip/pip3 installing pybluemonday multiple times with no change.

```
Traceback (most recent call last):
  File "ping.py", line 10, in <module>
    from CTFd.config import Config
  File "/opt/CTFd/CTFd/__init__.py", line 19, in <module>
    from CTFd.plugins import init_plugins
  File "/opt/CTFd/CTFd/plugins/__init__.py", line 9, in <module>
    from CTFd.utils.config.pages import get_pages
  File "/opt/CTFd/CTFd/utils/config/pages.py", line 6, in <module>
    from CTFd.utils.security.sanitize import sanitize_html
  File "/opt/CTFd/CTFd/utils/security/sanitize.py", line 1, in <module>
    from pybluemonday import UGCPolicy
ModuleNotFoundError: No module named 'pybluemonday'
```

I also tried updated the pybluemonday version from 0.0.4 to the latest version, 0.0.5 in the requirements documents, which also did not help.

**Comment by ColdHeat** [comment]
What happens if you do docker-compose build? There’s really no reason that
pybluemonday shouldn’t work on x86. Are you running pip in the container or
your host?

**Comment by cpsears** [comment]
I'll be honest, I didn't realize that docker-compose build was a command that existed. That fixed everything. Thank you so much!

**Comment by jontyrudman** [comment]
When using the Pi 3B and Docker (after a bit of tweaking to use piwheels), I get the following error:

```
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "ping.py", line 10, in <module>
ctfd_1   |     from CTFd.config import Config
ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 19, in <module>
ctfd_1   |     from CTFd.plugins import init_plugins
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/__init__.py", line 9, in <module>
ctfd_1   |     from CTFd.utils.config.pages import get_pages
ctfd_1   |   File "/opt/CTFd/CTFd/utils/config/pages.py", line 8, in <module>
ctfd_1   |     from CTFd.utils.security.sanitize import sanitize_html
ctfd_1   |   File "/opt/CTFd/CTFd/utils/security/sanitize.py", line 1, in <module>
ctfd_1   |     from pybluemonday import UGCPolicy
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pybluemonday/__init__.py", line 4, in <module>
ctfd_1   |     from pybluemonday.bluemonday import ffi, lib
ctfd_1   | ImportError: dynamic module does not define module export function (PyInit_bluemonday)
```

**Comment by yoni13** [comment]
> When using the Pi 3B and Docker (after a bit of tweaking to use piwheels), I get the following error:
> 
> ```
> ctfd_1   | Traceback (most recent call last):
> ctfd_1   |   File "ping.py", line 10, in <module>
> ctfd_1   |     from CTFd.config import Config
> ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 19, in <module>
> ctfd_1   |     from CTFd.plugins import init_plugins
> ctfd_1   |   File "/opt/CTFd/CTFd/plugins/__init__.py", line 9, in <module>
> ctfd_1   |     from CTFd.utils.config.pages import get_pages
> ctfd_1   |   File "/opt/CTFd/CTFd/utils/config/pages.py", line 8, in <module>
> ctfd_1   |     from CTFd.utils.security.sanitize import sanitize_html
> ctfd_1   |   File "/opt/CTFd/CTFd/utils/security/sanitize.py", line 1, in <module>
> ctfd_1   |     from pybluemonday import UGCPolicy
> ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pybluemonday/__init__.py", line 4, in <module>
> ctfd_1   |     from pybluemonday.bluemonday import ffi, lib
> ctfd_1   | ImportError: dynamic module does not define module export function (PyInit_bluemonday)
> ```
> 
> I'm assuming this has something to do with the issue?

Got the same results two years later on an armhf board, have you made it solved?

**Comment by ColdHeat** [comment]
pybluemonday is no longer in use and has been replaced with nh3 which I believe should work on arm.
