### ISSUE TITLE
serve.py crashes without any errors on Windows

### ISSUE THREAD

**Issue by benwoo1110** [CTFd/CTFd#1855]
**Environment**:

- CTFd Version/Commit: https://github.com/CTFd/CTFd/commit/d23f59dbd51925aac1aa6294c934d701953075d0
- Operating System: Windows 10, python 3.9.2
- Web Browser and Version: n/a

**What happened?**
Some errors from pybluemonday go code upon starting, see stacktrace below.

I reverted to the commit before pybluemonday was implemented https://github.com/CTFd/CTFd/commit/8de9819bd45be7483f252d37d0d0a2977dd7bd6d and it was able to start normally.

**What did you expect to happen?**
No errors and CTFd starts normally.

**How to reproduce your issue**
1. Install pip dependencies `pip install  -r requirements.txt`
2. Start with `python serve.py`

**Any associated stack traces or error logs**
```
PS C:\Users\Ben10\Documents\GitHub\CTFd> python serve.py
 * Importing gevent and monkey patching. Use --disable-gevent to disable.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6d2efafd]

goroutine 17 [running, locked to thread]:
github.com/microcosm-cc/bluemonday.(*Policy).init(...)
        C:/Users/RUNNER~1/AppData/Local/Temp/tmp4rqegntm/src/github.com/microcosm-cc/bluemonday/policy.go:173
github.com/microcosm-cc/bluemonday.(*Policy).AllowElements(0x0, 0xc0002b00e0, 0x1, 0x1, 0x0)
        C:/Users/RUNNER~1/AppData/Local/Temp/tmp4rqegntm/src/github.com/microcosm-cc/bluemonday/policy.go:488 +0x2d
reflect.Value.call(0x6d361b00, 0x0, 0x1613, 0x6d36825e, 0x4, 0xc000279e40, 0x1, 0x1, 0x6d3a4240, 0xc000064f60, ...)
        C:/hostedtoolcache/windows/go/1.14.12/x64/src/reflect/value.go:460 +0x8b2
reflect.Value.Call(0x6d361b00, 0x0, 0x1613, 0xc000279e40, 0x1, 0x1, 0x0, 0x1613, 0xc000279e80)
        C:/hostedtoolcache/windows/go/1.14.12/x64/src/reflect/value.go:321 +0xbb
main.CallPolicyFunctionWithString(0xc007fcfd52, 0x1e2469cabf0, 0x1e2469cac80)
        C:/Users/RUNNER~1/AppData/Local/Temp/tmp4rqegntm/src/github.com/ColdHeat/pybluemonday/bluemonday.go:145 +0x23c
main._cgoexpwrap_8294da18a757_CallPolicyFunctionWithString(0x1e207fcfd52, 0x1e2469cabf0, 0x1e2469cac80)
        _cgo_gotypes.go:163 +0x44
```

**Comment by ColdHeat** [comment]
Hi there, just wondering is there anything particularly special about your Windows installation? ARM or something like that?

**Comment by benwoo1110** [comment]
It's a Ryzen 7 2700x, and nothing special with my Windows 10 installed. Let be test on my secondary laptop running Windows 10 as well (x64-based as well).

**Comment by benwoo1110** [comment]
Same error from my laptop with Windows 10 and Ryzen 7 3700u.
Full setup + error logs: https://paste.lucko.me/Y45vcQmRHG

However, testing on my ubuntu VM, it runs successfully, so it may be a windows specific issue.

**Comment by benwoo1110** [comment]
In fact I tested just `pybluemonday` with sample code at the repo:
```python
from pybluemonday import UGCPolicy
s = UGCPolicy()

print(s.sanitize("<script>alert(1)</script><b class='stuff'>testing</b>"))
# <b>testing</b>

s.AllowAttrs("class", "style").Globally()
print(s.sanitize("<script>alert(1)</script><b class='stuff' style='color: red;'>testing</b>"))
# <b class="stuff" style="color: red;">testing</b>
```

Got the same error:
```
PS C:\Users\Ben10\Documents\GitHub\YCEP2021> python --version
Python 3.9.2
PS C:\Users\Ben10\Documents\GitHub\YCEP2021> python test.py  
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6d2f3271]

goroutine 17 [running, locked to thread]:
github.com/microcosm-cc/bluemonday.(*Policy).init(...)
        C:/Users/RUNNER~1/AppData/Local/Temp/tmp4rqegntm/src/github.com/microcosm-cc/bluemonday/policy.go:173
github.com/microcosm-cc/bluemonday.(*Policy).sanitize(0x0, 0x6d3a0fe0, 0xc000290380, 0x35)
        C:/Users/RUNNER~1/AppData/Local/Temp/tmp4rqegntm/src/github.com/microcosm-cc/bluemonday/sanitize.go:190 +0x41
github.com/microcosm-cc/bluemonday.(*Policy).Sanitize(0x0, 0xc000011580, 0x35, 0x6d4be0a0, 0x0)
        C:/Users/RUNNER~1/AppData/Local/Temp/tmp4rqegntm/src/github.com/microcosm-cc/bluemonday/sanitize.go:63 +0xae
main.SanitizeWithPolicy(0xc007fcfd52, 0x21c90e427d0, 0x0)
        C:/Users/RUNNER~1/AppData/Local/Temp/tmp4rqegntm/src/github.com/ColdHeat/pybluemonday/bluemonday.go:166 +0x94
main._cgoexpwrap_8294da18a757_SanitizeWithPolicy(0x21c07fcfd52, 0x21c90e427d0, 0x0)
        _cgo_gotypes.go:192 +0x6f
PS C:\Users\Ben10\Documents\GitHub\YCEP2021> 
```

**Comment by benwoo1110** [comment]
Hmm sure I can test that, but the second laptop I tested with was using python 3.8 tho.

**Comment by benwoo1110** [comment]
@ColdHeat I see that you have committed something to fix the issue, is there a way I can test it? Thanks!

**Comment by ColdHeat** [comment]
I'm not sure if you can see the generated artifacts here: https://github.com/ColdHeat/pybluemonday/pull/13/checks or on your recent PR https://github.com/ColdHeat/pybluemonday/pull/17/checks. 

Here's a link to the zip. You'll need to install the relevant whl and probably directly call into it with the sample code. 
https://file.io/vIOlkOv2hWgG

**Comment by benwoo1110** [comment]
Thanks for the quick response, I have manually installed the whl and it worked with the sample code with from `pybluemonday` repo. 

However for some reason, when using with CTFd, it stops at `INFO  [werkzeug]  * Restarting with stat` and the program end. The only way to fix it was to comment out the pybluemondey code.

Logs: https://paste.lucko.me/nVCRJ3SplH

**Comment by ColdHeat** [comment]
Can you try running with `--disable-gevent`? I saw some discussion online that said that could be an issue. 

Overall, Windows isn't likely going to be a well supported platform target going forward but I'll try to see what I can do to get this situation working.

**Comment by benwoo1110** [comment]
Sadly `--disable-gevent` did not fix it:
```
PS C:\Users\Ben10\Documents\GitHub\CTFd> python .\serve.py --disable-gevent
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
 * Loaded module, <module 'CTFd.plugins.challenges' from 'C:\\Users\\Ben10\\Documents\\GitHub\\CTFd\\CTFd\\plugins\\challenges\\__init__.py'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from 'C:\\Users\\Ben10\\Documents\\GitHub\\CTFd\\CTFd\\plugins\\dynamic_challenges\\__init__.py'>
 * Loaded module, <module 'CTFd.plugins.flags' from 'C:\\Users\\Ben10\\Documents\\GitHub\\CTFd\\CTFd\\plugins\\flags\\__init__.py'>
 * Serving Flask app "CTFd" (lazy loading)
 * Environment: development
 * Debug mode: on
INFO  [werkzeug]  * Restarting with stat
PS C:\Users\Ben10\Documents\GitHub\CTFd>
```

**Comment by ColdHeat** [comment]
After digging through this for awhile, can you try running `flask run` instead of `serve.py`?

The latest pybluemonday wheels work just fine on Windows but I think something about flask run works better on Windows. Technically it's the recommended approach for dev servers according to the Flask docs anyway. https://flask.palletsprojects.com/en/1.1.x/server/

**Comment by ColdHeat** [comment]
Linking a bunch of potentially related issues:

https://github.com/CTFd/CTFd/issues/1099
https://github.com/pallets/flask/issues/2460

**Comment by ColdHeat** [comment]
I believe there's some sort of issue with serve.py preventing it from working under Windows. 

The pybluemonday wheel currently is broken but that issue was fixed but just needs a new wheel. However I currently see the behavior where Python crashes without any reason. I can't reproduce this elsewhere but it seems to be resolved by using `flask run`.

I'll leave this open but this no longer seems to be an error in CTFd. 

I'll release a new version of pybluemonday and and bump the version here eventually.

**Comment by benwoo1110** [comment]
Yep flash run did the trick! Thank you for helping, appreciate it.

Logs for reference: https://paste.lucko.me/STF8S7EOgo

**Comment by ColdHeat** [comment]
I believe this is the actual issue: https://github.com/pallets/werkzeug/issues/2076

**Comment by Vijay1667** [comment]
I am using virtual environment in python.
after the python serve.py I tried flask run, but in 127.0.0.1:4000, it is showing flask.cli.NoAppException: Could not import "hello". I have deleted the environment variable. what should I set the environment variable as ??
![image](https://user-images.githubusercontent.com/95224492/203490809-7225ddf7-a035-447a-bfb5-a61eb4e01e98.png)
