### ISSUE TITLE
docker container fails to start "Can't load plugin: sqlalchemy.dialects:mysql.pymsql"

### ISSUE THREAD

**Issue by maxdotdotg** [CTFd/CTFd#1930]
**Environment**:

- CTFd Version/Commit: git tag `3.3.0` and `ctfd/ctfd:mark-3.3.0`
- Operating System: container from dockerhub `ctfd/ctfd:mark-3.3.0` and container build from git tag `3.3.0`, commit `a33a31b`
- Web Browser and Version: n/a

**What happened?**
when I run the container and pass `DATABASE_URL` as an env var, the container fails to start

**What did you expect to happen?**
the container to start

**How to reproduce your issue**
run the container and pass DATABASE_URL as an env var: `docker run --rm -it -p 8000:8000 --env DATABASE_URL="mysql+pymsql://user:pass@remote_host" ctfd/ctfd:mark-3.3.0`

**Any associated stack traces or error logs**
``` bash
# using container from dockerhub
➜  CTFd git:(a33a31b) docker run --rm -it -p 8000:8000 --env DATABASE_URL="mysql+pymsql://user:pass@terraform-20210701234905073500000001.eh4syauh.us-east-1.rds.amazonaws.com:3306" ctfd/ctfd:mark-3.3.0
Waiting for terraform-20210701234905073500000001.eh4syauh.us-east-1.rds.amazonaws.com:3306 to be ready
terraform-20210701234905073500000001.eh4syauh.us-east-1.rds.amazonaws.com is ready
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    app = create_app()
  File "/opt/CTFd/CTFd/__init__.py", line 199, in create_app
    url = create_database()
  File "/opt/CTFd/CTFd/utils/migrations/__init__.py", line 24, in create_database
    if not database_exists_util(url):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/functions/database.py", line 470, in database_exists
    engine = sa.create_engine(url)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 488, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 268, in load
    "Can't load plugin: %s:%s" % (self.group, name)
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mysql.pymsql
```

``` bash
# using container built locally from source
➜  CTFd git:(a33a31b) docker run --rm -it -p 8000:8000 --env DATABASE_URL="mysql+pymsql://user:pass@terraform-20210701234905073500000001.eh4syauh.us-east-1.rds.amazonaws.com:3306" ctfd-from-source:3.3.0
Waiting for terraform-20210701234905073500000001.eh4syauh.us-east-1.rds.amazonaws.com:3306 to be ready
terraform-20210701234905073500000001.eh4syauh.us-east-1.rds.amazonaws.com is ready
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    app = create_app()
  File "/opt/CTFd/CTFd/__init__.py", line 199, in create_app
    url = create_database()
  File "/opt/CTFd/CTFd/utils/migrations/__init__.py", line 24, in create_database
    if not database_exists_util(url):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/functions/database.py", line 470, in database_exists
    engine = sa.create_engine(url)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 488, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 268, in load
    "Can't load plugin: %s:%s" % (self.group, name)
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mysql.pymsql
```

**Comment by maxdotdotg** [comment]
ah, for the love of typos 😓 so so sorry, `pymsql` should have been `py*my*ql`
