### ISSUE TITLE
Error 500 when visiting /admin/users/1 - AttributeError: 'NoneType' object has no attribute 'get_score'

### ISSUE THREAD

**Issue by phretor** [CTFd/CTFd#1932]
**Environment**:

- CTFd Version/Commit: HEAD
- Operating System: Docker image based off official Dockerfile
- Web Browser and Version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

**What happened?**
500 Internal server error

**What did you expect to happen?**
Show the admin user details when in team mode

**How to reproduce your issue**
* visited the `/admin/users/1`
* this seems due to the fact that, when in team mode, the admin user does not belong to any team and, for some reason, this one returns `None`

```python
    @hybrid_property
    def account(self):
        from CTFd.utils import get_config

        user_mode = get_config("user_mode")
        if user_mode == "teams":
            return self.team
        elif user_mode == "users":
            return self
```

**Any associated stack traces or error logs**
```
ERROR [CTFd] Exception on /admin/users/1 [GET]
--
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
return original_handler(e)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 133, in admins_only_wrapper
return f(*args, **kwargs)
File "/opt/CTFd/CTFd/admin/users.py", line 91, in users_detail
score = user.account.get_score(admin=True)
AttributeError: 'NoneType' object has no attribute 'get_score'
```

**Comment by ColdHeat** [comment]
I believe #1934 should fix this. The change was to have user pages show the team's score/place instead of their individual score/place. 

If a user doesn't have a team, they shouldn't have an "account" so they shouldn't have a score/place.

**Comment by phretor** [comment]
I confirm this has been fixed. BTW, is there an auto-build set in Docker Hub to keep the `ctfd/ctfd:latest` aligned with HEAD?

**Comment by ColdHeat** [comment]
I believe there is but I know Docker has recently changed the autobuild system. I have not verified that it is still working but no one has really reported an issue either.
