### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'Configs' is undefined

### ISSUE THREAD

**Issue by evandrix** [CTFd/CTFd#2001]
I'm ambitiously trying to setup (for fun) without the help of `docker` or `docker-compose`.

- MacOSX Big Sur 11.6
- Python 3.9.7

I managed to install all the required dependencies (I also didn't follow the locked versions i.e. `==` in requirements.txt, instead I'm just going with the latest i.e. `pip install -U`), and either `python3 -B -u serve.py --disable-gevent` or `flask run` works, but http://127.0.0.1:4000/setup

To get it to run in the first place, I made minor replacements, e.g.

- `ma.ModelSchema` => `ma.SQLAlchemyAutoSchema`
- `validate.Email("Emails must be a properly formatted email address")` => `validate.Email(error="Emails must be a properly formatted email address")`
- `name = fields.Nested(FieldSchema, only=("name"), attribute="field")` => `name = fields.Nested(FieldSchema, only=("name",), attribute="field")`

> jinja2.exceptions.UndefinedError
> jinja2.exceptions.UndefinedError: 'Configs' is undefined
> 
> Traceback (most recent call last)
> File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
> return self.wsgi_app(environ, start_response)
> File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
> response = self.handle_exception(e)Open an interactive python shell in this frame
> File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 672, in error_router
> return original_handler(e)
> File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 672, in error_router
> return original_handler(e)
> File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
> rv = self.dispatch_request()
> File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
> return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
> File "/Users/user/Downloads/CTFd/CTFd/views.py", line 261, in setup
> return render_template("setup.html", state=serialize(generate_nonce()))
> File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
> return _render(
> File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
> rv = template.render(context)
> File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
> self.environment.handle_exception()
> File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
> raise rewrite_traceback_stack(source=source)
> File "/Users/user/Downloads/CTFd/CTFd/themes/core/templates/setup.html", line 1, in top-level template code
> {% extends "base.html" %}
> File "/Users/user/Downloads/CTFd/CTFd/themes/core/templates/base.html", line 4, in top-level template code
> <title>{{ Configs.ctf_name }}</title>
> File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
> value = getattr(obj, attribute)
> jinja2.exceptions.UndefinedError: 'Configs' is undefined
> The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
> To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.
> 
> You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:
> 
> dump() shows all variables in the frame
> dump(obj) dumps all that's known about the object
> Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

I managed to track it down to the usage of `Configs.ctf_name` inside base.html, which setup.html extends in the template, but my troubleshooting and familiarity with `jinja2` templating is only up to this point. If anyone is able to quickly identify with what I'm experiencing, and have an idea, much appreciated.

**Comment by ColdHeat** [comment]
This seems interesting since perhaps we can update some of the versions. 

You can look at the initialization code here to see how its passed to Jinja: https://github.com/CTFd/CTFd/blob/514ab2c8bd3b0687615307c19fa9618b09e3998a/CTFd/utils/initialization/__init__.py#L104-L110. I haven't tried upgrading dependencies because some of them are major version changes so I don't know what the issue might be.

**Comment by evandrix** [comment]
alright sure, thanks for the pointer in the right direction :)

**Comment by evandrix** [comment]
attempted to adapt https://stackoverflow.com/questions/43335931#43336023 with success \o/

add to [/CTFd/views.py](/CTFd/views.py):
```
@app.context_processor
def tpl_inject_globals(): return app.jinja_env.globals
```
