### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by tcccorp** [CTFd/CTFd#2042]
**Environment**:

- CTFd Version/Commit: last version but I don't know the previous version 
- Operating System: debian 10
- Web Browser and Version:

**What happened?**
After a git pull, I tried to launch the server.  there was a message about a migration, I accepted the migration but just after there was a error message as you can see below Did you already see this error ?

**What did you expect to happen?**

just python3 serve.py or flask run 

**How to reproduce your issue**

```
sqlalchemy.exc.OperationalError
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: challenges.connection_info
[SQL: SELECT count(*) AS count_1 
FROM (SELECT challenges.id AS challenges_id, challenges.name AS challenges_name, challenges.description AS challenges_description, challenges.connection_info AS challenges_connection_info, challenges.max_attempts AS challenges_max_attempts, challenges.value AS challenges_value, challenges.category AS challenges_category, challenges.type AS challenges_type, challenges.state AS challenges_state, challenges.requirements AS challenges_requirements 
FROM challenges) AS anon_1]
(Background on this error at: http://sqlalche.me/e/e3q8)

Traceback (most recent call last)
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
cursor, statement, parameters, context
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute
cursor.execute(statement, parameters)
The above exception was the direct cause of the following exception:
File "/root/CTFd_14012022/wsgi.py", line 11, in <module>
app = create_app()
File "/root/CTFd_14012022/CTFd/__init__.py", line 271, in create_app
update_check(force=True)
File "/root/CTFd_14012022/CTFd/utils/updates/__init__.py", line 47, in update_check
"challenge_count": Challenges.query.count(),
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3749, in count
return self.from_self(col).scalar()
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3469, in scalar
ret = self.one()
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3436, in one
ret = self.one_or_none()
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3405, in one_or_none
ret = list(self)
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3481, in __iter__
return self._execute_and_instances(context)
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1020, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
distilled_params,
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
e, statement, parameters, cursor, context
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
sqlalchemy_exception, with_traceback=exc_info[2], from_=e
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
raise exception
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
cursor, statement, parameters, context
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: challenges.connection_info
[SQL: SELECT count(*) AS count_1
FROM (SELECT challenges.id AS challenges_id, challenges.name AS challenges_name, challenges.description AS challenges_description, challenges.connection_info AS challenges_connection_info, challenges.max_attempts AS challenges_max_attempts, challenges.value AS challenges_value, challenges.category AS challenges_category, challenges.type AS challenges_type, challenges.state AS challenges_state, challenges.requirements AS challenges_requirements
FROM challenges) AS anon_1]
(Background on this error at: http://sqlalche.me/e/e3q8)
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
```

**Comment by ColdHeat** [comment]
Are you using SQLite as your database backend? 

Can you try:

1. Revert back to the original version of CTFd
2.  Generating an export
3. Upgrading CTFd to the current version 
4. Importing your backup

**Comment by tcccorp** [comment]
hello ColdHeat, 

Thanks  to your answer.  I tried to import a backup but it failed. As there was a CTF, I installed the latest version and build if from scratch .
