### ISSUE TITLE
Path doesn't exist: '/migrations', with Apache + mod_wsgi deployment

### ISSUE THREAD

**Issue by iqlusi0n** [CTFd/CTFd#2043]
**Environment**:

- CTFd Version/Commit: f89fcea1e20335943cf3f806ba2c5db5978fcfdb
- Operating System: Debian 11 x86_64
- Web Browser and Version: Mozilla Firefox 91.5.0esr
- Webserver: Apache/2.4.52 (Debian)
- Database: mariadb  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
- Python 3.9.2
- Pip Packages: 
alembic                1.4.3
aniso8601              8.0.0
attrs                  20.3.0
bcrypt                 3.1.7
boto3                  1.13.9
botocore               1.16.26
certifi                2020.11.8
cffi                   1.14.3
chardet                3.0.4
chrome-gnome-shell     0.0.0
click                  7.1.2
cmarkgfm               0.4.2
cupshelpers            1.0
dataset                1.3.1
dbus-python            1.2.16
distro                 1.5.0
distro-info            1.0
docutils               0.15.2
Flask                  1.1.2
Flask-Caching          1.8.0
flask-marshmallow      0.10.1
Flask-Migrate          2.5.3
flask-restx            0.5.1
Flask-Script           2.0.6
Flask-SQLAlchemy       2.4.3
gevent                 20.9.0
greenlet               0.4.17
gunicorn               20.0.4
httplib2               0.18.1
idna                   2.10
itsdangerous           1.1.0
Jinja2                 2.11.3
jmespath               0.10.0
jsonschema             3.2.0
Mako                   1.1.3
MarkupSafe             1.1.1
marshmallow            2.20.2
marshmallow-sqlalchemy 0.17.0
maxminddb              1.5.4
mysqlclient            2.1.0
passlib                1.7.2
pip                    20.3.4
pybluemonday           0.0.8
pycairo                1.16.2
pycparser              2.20
pycups                 2.0.1
pycurl                 7.43.0.6
pydantic               1.6.2
PyGObject              3.38.0
PyMySQL                0.9.3
pyrsistent             0.17.3
PySimpleSOAP           1.16.2
pysmbc                 1.0.23
python-apt             2.2.1
python-dateutil        2.8.1
python-debian          0.1.39
python-debianbts       3.1.0
python-dotenv          0.13.0
python-editor          1.0.4
python-geoacumen-city  0.0.1
pytz                   2020.4
pyxdg                  0.27
redis                  3.5.2
reportbug              7.10.3+deb11u1
requests               2.23.0
s3transfer             0.3.3
setuptools             52.0.0
six                    1.15.0
SQLAlchemy             1.3.17
SQLAlchemy-Utils       0.36.6
tenacity               6.2.0
unattended-upgrades    0.1
urllib3                1.25.11
Werkzeug               1.0.1
wheel                  0.34.2
WTForms                2.3.1
xdg                    5
zope.event             4.5.0
zope.interface         5.2.0

**What happened?**
Trying to deploy CTFd using Apache with mod_wsgi, Mariadb, and mysqlclient, leads to an error (listed below). Which seems to imply it can't find the migrations folder for setting up the database.

**How to reproduce your issue**
With the environment listed previously, use this for the apache conf file for the website:
```
<VirtualHost *>
    WSGIDaemonProcess ctfd user=www-data group=www-data threads=5
    WSGIScriptAlias / /var/www/ctfd/ctfd.wsgi
 
    <Directory /var/www/ctfd/>
        WSGIProcessGroup ctfd
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from all
    </Directory>
</VirtualHost>
```
ctfd.wsgi contents:
```
import sys

sys.path.insert(0, '/var/www/ctfd/')

from CTFd import create_app

app = create_app()
```

**Any associated stack traces or error logs**
The following was in the Apache error.log (with timestamp prefixes removed):
```
Error: Path doesn't exist: '/migrations'.  Please use the 'init' command to create a new scripts folder.
mod_wsgi (pid=2206): SystemExit exception raised when doing exec of Python script file '/var/www/ctfd/ctfd.wsgi'.
mod_wsgi (pid=2206): SystemExit exception raised by WSGI script '/var/www/ctfd/ctfd.wsgi' ignored.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.9/dist-packages/alembic/command.py", line 278, in upgrade
    script = ScriptDirectory.from_config(config)
  File "/usr/local/lib/python3.9/dist-packages/alembic/script/base.py", line 139, in from_config
    return ScriptDirectory(
  File "/usr/local/lib/python3.9/dist-packages/alembic/script/base.py", line 67, in __init__
    raise util.CommandError(
alembic.util.exc.CommandError: Path doesn't exist: '/migrations'.  Please use the 'init' command to create a new scripts folder.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/ctfd/ctfd.wsgi", line 7, in <module>
    app = create_app()
  File "/var/www/ctfd/CTFd/__init__.py", line 231, in create_app
    upgrade()
  File "/usr/local/lib/python3.9/dist-packages/flask_migrate/__init__.py", line 99, in wrapped
    sys.exit(1)
SystemExit: 1
```

**Comment by iqlusi0n** [comment]
Seems like #257 might have been related.

**Comment by ColdHeat** [comment]
I don't particularly understand the migrations issue as migrations should be working properly with the standard Docker deployment strategy. The path `'/migrations'` should be the full path to the migrations folder and I don't understand why it's not using the actual full path. Perhaps it's something to do with `mod_wsgi` and haven't for a very long time I can't really comment on why that might be.  

As for the timeout issue you can try disabling `SERVER_SENT_EVENTS` or getting Apache to properly handle Server Sent Events (SSE) for the `/events` endpoint. See https://github.com/CTFd/CTFd/blob/f89fcea1e20335943cf3f806ba2c5db5978fcfdb/conf/nginx/http.conf#L23-L36 for how this is done in nginx. 

In my opinion you'd be better served simply using nginx or the docker-compose based deployment provided in the repo.

**Comment by ColdHeat** [comment]
Yeah nginx is generally the preferred reverse proxy server at this point so there's really not much support for Apache + mod_wsgi.

I would take a PR assuming it doesn't have a hard coded path and wasn't too complicated. We're relying on the defaults of the migration library so I'm inclined to think that the issue lies somewhere in your configs.
