### ISSUE TITLE
Export from 3.4.3 causing missing content when imported into 3.5.0

### ISSUE THREAD

**Issue by huornlmj** [CTFd/CTFd#2121]
**Environment**:

- CTFd Version/Commit: 3.5.0
- Operating System: Ubuntu
- Web Browser and Version: Vivaldi

**What happened?**
Exported backup from 3.4.3 (using official Docker images) when imported into 3.5.0 container results is many error 500's, chalenges page empty, only three user accounts visible from around 10, system admin panel not available.

**What did you expect to happen?**
Import should work between versions.

**How to reproduce your issue**
Uncertain.

**Any associated stack traces or error logs**

```
ERROR [CTFd] Exception on /api/v1/challenges [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: challenges.next_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/CTFd/CTFd/utils/decorators/visibility.py", line 64, in _check_challenge_visibility
    return f(*args, **kwargs)
  File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 23, in during_ctf_time_only_wrapper
    return f(*args, **kwargs)
  File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 72, in _require_verified_emails
    return f(*args, **kwargs)
  File "/opt/CTFd/CTFd/api/v1/helpers/request.py", line 56, in wrapper
    return func(*args, loaded, **kwargs)
  File "/opt/CTFd/CTFd/api/v1/challenges.py", line 236, in get
    for challenge in chal_q:
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1323, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1517, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: challenges.next_id
[SQL: SELECT challenges.id AS challenges_id, challenges.name AS challenges_name, challenges.description AS challenges_description, challenges.connection_info AS challenges_connection_info, challenges.next_id AS challenges_next_id, challenges.max_attempts AS challenges_max_attempts, challenges.value AS challenges_value, challenges.category AS challenges_category, challenges.type AS challenges_type, challenges.state AS challenges_state, challenges.requirements AS challenges_requirements
FROM challenges
WHERE challenges.state != ? AND challenges.state != ? ORDER BY challenges.value, challenges.id]
[parameters: ('hidden', 'locked')]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by ColdHeat** [comment]
The recommended database to use is MySQL (https://docs.ctfd.io/docs/deployment/installation#database-server). Imports on SQLite are known to not necessarily be stable because of SQLite's lack of ALTER TABLE. 

See #1988.

**Comment by ColdHeat** [comment]
Also it should be noted that if the import is mentioning an End Time it means the import has completed, whether successfully or not. Perhaps we can improve some of the usability there.

**Comment by huornlmj** [comment]
> The recommended database to use is MySQL (https://docs.ctfd.io/docs/deployment/installation#database-server). Imports on SQLite are known to not necessarily be stable because of SQLite's lack of ALTER TABLE.
> 
> See #1988.

The database used in 3.4.3 and 3.5.0 are both supplied in the official Dockerhub CTFd image. I do not control this.  I believe that the official Docker CTFd image used SQlite for both versions, not MySQL.

**Comment by bkimminich** [comment]
The root cause is the missing `next_id` field as mentioneid in the log when you export from 3.4.x. I've run into the same error with https://github.com/juice-shop/juice-shop-ctf. Once I added `next_id: null` to all challenges in the `challenges.json`, importing to 3.5 works fine again.

Maybe this could happen on-the-fly during import on CTFd-side, or old backups might have to be rejected at least, pointing out the version they were made for?

**Comment by bkimminich** [comment]
It then works fine again *in the plain Docker image*, I should have added.

**Comment by ColdHeat** [comment]
Importing should work fine on a MySQL/MariaDB database. The intention of the import/export system is to be able to save data from an older version and then install it on a newer version. 

It isn't intended for people making modifications to imports or custom building imports but it is doable in theory. 

I feel the issue here is related mostly to sqlite because we can't do migrations on sqlite easily. The plain Docker image bundles sqlite just b/c it's easier. And it's easier to put MySQL on a seperate container and use it via docker-compose.

**Comment by huornlmj** [comment]
Should the Docker Hub image (https://hub.docker.com/r/ctfd/ctfd) then not be updated to remove the built-in sqlite database?
