### ISSUE TITLE
when execute python3 serve.py then "ImportError: cannot import name 'monotonic_ns'"

### ISSUE THREAD

**Issue by striver619** [CTFd/CTFd#2235]
**Environment**:
```
[root@wm-c7-ctfd-2 CTFd]# cat /etc/system-release
CentOS Linux release 7.9.2009 (AltArch)
[root@wm-c7-ctfd-2 CTFd]# arch
aarch64
[root@wm-c7-ctfd-2 CTFd]# cat /proc/cpuinfo |grep processor|wc -l
8
[root@wm-c7-ctfd-2 CTFd]# free -h
              total        used        free      shared  buff/cache   available
Mem:            14G        966M        6.9G        799M        6.8G         12G
Swap:          2.1G          0B        2.1G
[root@wm-c7-ctfd-2 CTFd]# python3 -V
Python 3.6.8
[root@wm-c7-ctfd-2 CTFd]#
```

- CTFd Version:
latest
```
git clone https://github.com/CTFd/CTFd.git
```

**What happened?**
when I execute ```python3 serve.py```
it will appear:
```
[root@wm-c7-ctfd-2 CTFd]# python3 serve.py
 * Importing gevent and monkey patching. Use --disable-gevent to disable.
Traceback (most recent call last):
  File "serve.py", line 21, in <module>
    from CTFd import create_app
  File "/usr/local/CTFd/CTFd/CTFd/__init__.py", line 16, in <module>
    import CTFd.utils.config
  File "/usr/local/CTFd/CTFd/CTFd/utils/__init__.py", line 9, in <module>
    from CTFd.cache import cache
  File "/usr/local/CTFd/CTFd/CTFd/cache/__init__.py", line 4, in <module>
    from time import monotonic_ns
ImportError: cannot import name 'monotonic_ns'
[root@wm-c7-ctfd-2 CTFd]#
```

**What did you expect to happen?**
I hope that someone will do me a favour!

**How to reproduce your issue**
when execute python3 serve.py then "ImportError: cannot import name 'monotonic_ns'"

**Comment by striver619** [comment]
I hope that someone will do me a favour!

**Comment by striver619** [comment]
> Upgrade to Python 3.7: https://docs.python.org/3/library/time.html#time.monotonic_ns
> 
> Python 3.6 is EOL: https://endoflife.date/python

thank you very much!

I have already used Python3.8.5 to solve this issue!
