### ISSUE TITLE
Scoreboard shows "No solves yet", even though there are solves

### ISSUE THREAD

**Issue by AndersFelde** [CTFd/CTFd#2496]
**Environment**:

- CTFd Version/Commit: 3.7.0, commit: `6ce3eb10745283c57f2ef1aa1119ae46961a3bc3`
- Operating System: Arch Linux
- Web Browser and Version: Brave Browser 122.1.63.174

**What happened?**

Scoreboard shows "No solves yet". Even though there are solves

![image](https://github.com/CTFd/CTFd/assets/49548776/e11b89b7-848b-4ae6-89f1-be48b4180a54)

**What did you expect to happen?**

Should show scoreboard

**How to reproduce your issue**

visit /scoreboard

**Any associated stack traces or error logs**

Found this error in logs

```
2024-03-15T20:00:05.645078663Z [2024-03-15 20:00:05 +0000] [20] [ERROR] Error handling request
2024-03-15T20:00:05.645120601Z Traceback (most recent call last):
2024-03-15T20:00:05.645128737Z   File "/opt/venv/lib/python3.11/site-packages/gunicorn/workers/base_async.py", line 113, in handle_request
2024-03-15T20:00:05.645138815Z     resp.write_file(respiter)
2024-03-15T20:00:05.645146219Z   File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 385, in write_file
2024-03-15T20:00:05.645154274Z     if not self.sendfile(respiter):
2024-03-15T20:00:05.645157951Z            ^^^^^^^^^^^^^^^^^^^^^^^
2024-03-15T20:00:05.645161298Z   File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 375, in sendfile
2024-03-15T20:00:05.645164844Z     self.sock.sendfile(respiter.filelike, count=nbytes)
2024-03-15T20:00:05.645168231Z   File "/opt/venv/lib/python3.11/site-packages/gevent/_socket3.py", line 486, in sendfile
2024-03-15T20:00:05.645171497Z     return self._sendfile_use_send(file, offset, count)
2024-03-15T20:00:05.645175344Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-15T20:00:05.645179743Z   File "/opt/venv/lib/python3.11/site-packages/gevent/_socket3.py", line 416, in _sendfile_use_send
2024-03-15T20:00:05.645191805Z     self._check_sendfile_params(file, offset, count)
2024-03-15T20:00:05.645197536Z   File "/opt/venv/lib/python3.11/site-packages/gevent/_socket3.py", line 461, in _check_sendfile_params
2024-03-15T20:00:05.645202324Z     raise ValueError(
2024-03-15T20:00:05.645207635Z ValueError: count must be a positive integer (got 0)
```

API request to `/api/v1/scoreboard/top/10` returns
```json
{"success": true, "data": {}}
```

**Comment by Unknowndotexe** [comment]
I have the same issue, did you solve the problem? (CTF Version 3.7.2)

> ctfd_1   | [2024-07-03 17:15:30 +0000] [19] [ERROR] Error handling request
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/gunicorn/workers/base_async.py", line 113, in handle_request
ctfd_1   |     resp.write_file(respiter)
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 385, in write_file
ctfd_1   |     if not self.sendfile(respiter):
ctfd_1   |            ^^^^^^^^^^^^^^^^^^^^^^^
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 375, in sendfile
ctfd_1   |     self.sock.sendfile(respiter.filelike, count=nbytes)
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/gevent/_socket3.py", line 486, in sendfile
ctfd_1   |     return self._sendfile_use_send(file, offset, count)
ctfd_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/gevent/_socket3.py", line 416, in _sendfile_use_send
ctfd_1   |     self._check_sendfile_params(file, offset, count)
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/gevent/_socket3.py", line 461, in _check_sendfile_params
ctfd_1   |     raise ValueError(
ctfd_1   | ValueError: count must be a positive integer (got 0)
