### ISSUE TITLE
v3.7.1  pymysql.err.OperationalError: (1050, "Table 'brackets' already exists")

### ISSUE THREAD

**Issue by Pd1r** [CTFd/CTFd#2556]
ctfd_1   | Waiting for db to be ready
ctfd_1   | db is ready
ctfd_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
ctfd_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ctfd_1   | INFO  [alembic.runtime.migration] Running upgrade 5c4996aeb2cb -> 9889b8c53673, Add Brackets table
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
ctfd_1   |     self.dialect.do_execute(
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
ctfd_1   |     cursor.execute(statement, parameters)
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/pymysql/cursors.py", line 148, in execute
ctfd_1   |     result = self._query(query)
ctfd_1   |              ^^^^^^^^^^^^^^^^^^
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/pymysql/cursors.py", line 310, in _query
ctfd_1   |     conn.query(q)
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 548, in query
ctfd_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
ctfd_1   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_query_result
ctfd_1   |     result.read()
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 1156, in read
ctfd_1   |     first_packet = self.connection._read_packet()
ctfd_1   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 725, in _read_packet
ctfd_1   |     packet.raise_for_error()
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error
ctfd_1   |     err.raise_mysql_exception(self._data)
ctfd_1   |   File "/opt/venv/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
ctfd_1   |     raise errorclass(errno, errval)
ctfd_1   | pymysql.err.OperationalError: (1050, "Table 'brackets' already exists")

**Comment by hassannawaz1210** [comment]
bump

**Comment by ColdHeat** [comment]
See https://github.com/CTFd/CTFd/pull/2601/commits/d659f43f8798bf563a1e1917b0364b92310b16e5 and https://github.com/CTFd/CTFd/issues/2600#issuecomment-2365065037 to get MariaDB working properly under Windows Docker Desktop with WSL2.
