### ISSUE TITLE
Dockerized CTFd fails to start when config option missing, does not fall back to env

### ISSUE THREAD

**Issue by maciejopalinski** [CTFd/CTFd#2582]
**Environment**:

- CTFd Version/Commit: https://hub.docker.com/layers/ctfd/ctfd/3.7.3/images/sha256-5179a677572afac645850ca9df681a8f67ac29c7c220f775e8259b913c8a7157?context=explore
- Operating System: Linux
- Web Browser and Version: unrelated

**What happened?**
CTFd fails to start when configuration options are missing from config.ini. It does not fall back to environmental variables. It fails even if `DATABASE_URL` env variable **is** provided. It does **not** fail when DATABASE_URL is left empty in config.ini, then it correctly falls back to using env.

```
Traceback (most recent call last):
2024-08-13T06:15:38.819526053Z   File "/opt/CTFd/ping.py", line 10, in <module>
2024-08-13T06:15:38.819532325Z     from CTFd.config import Config
2024-08-13T06:15:38.819535373Z   File "/opt/CTFd/CTFd/config.py", line 84, in <module>
2024-08-13T06:15:38.819542027Z     class ServerConfig(object):
2024-08-13T06:15:38.819545295Z   File "/opt/CTFd/CTFd/config.py", line 88, in ServerConfig
2024-08-13T06:15:38.819581297Z     DATABASE_URL: str = empty_str_cast(config_ini["server"]["DATABASE_URL"])
2024-08-13T06:15:38.819637957Z                                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
2024-08-13T06:15:38.819666487Z   File "/usr/local/lib/python3.11/configparser.py", line 1275, in __getitem__
    raise KeyError(key)
2024-08-13T06:15:38.820201429Z KeyError: 'DATABASE_URL'
```

**What did you expect to happen?**
CTFd should start even if config parameters are not present in config.ini. It needs to fall back to env.

**How to reproduce your issue**
1. Follow instructions from https://github.com/bman46/CTFd-Helm/
2. `config.enable: true` https://github.com/bman46/CTFd-Helm/blob/8f106be62e4a7408c46452729d4bf8e8a8674ea5/values.yaml#L71
3. Install helm app
4. Kubernetes pod will not start, because it does not have DATABASE_URL in config.ini, despite having DATABASE_URL env variable.
5. Replace `config.settings` with the following:
```
    [server]
    SECRET_KEY = 
    DATABASE_URL =
    DATABASE_HOST =
    DATABASE_PROTOCOL =
    DATABASE_USER =
    DATABASE_PASSWORD =
    DATABASE_PORT =
    DATABASE_NAME =
    REDIS_URL =
    REDIS_HOST =
    REDIS_PROTOCOL =
    REDIS_USER =
    REDIS_PASSWORD =
    REDIS_PORT =
    REDIS_DB =
    [security]
    SESSION_COOKIE_HTTPONLY = true
    SESSION_COOKIE_SAMESITE = Lax
    PERMANENT_SESSION_LIFETIME = 604800
    CROSS_ORIGIN_OPENER_POLICY =
    [email]
    MAILFROM_ADDR =
    MAIL_SERVER =
    MAIL_PORT =
    MAIL_USEAUTH =
    MAIL_USERNAME =
    MAIL_PASSWORD =
    MAIL_TLS =
    MAIL_SSL =
    MAILSENDER_ADDR =
    MAILGUN_API_KEY =
    MAILGUN_BASE_URL =
    MAIL_PROVIDER =
    [uploads]
    UPLOAD_PROVIDER =
    UPLOAD_FOLDER =
    AWS_ACCESS_KEY_ID =
    AWS_SECRET_ACCESS_KEY =
    AWS_S3_BUCKET =
    AWS_S3_ENDPOINT_URL =
    AWS_S3_REGION =
    AWS_S3_ADDRESSING_STYLE =
    AWS_S3_CUSTOM_DOMAIN =
    AWS_S3_CUSTOM_PREFIX =
    [logs]
    LOG_FOLDER =
    [optional]
    REVERSE_PROXY =
    THEME_FALLBACK =
    TEMPLATES_AUTO_RELOAD =
    SQLALCHEMY_TRACK_MODIFICATIONS =
    SWAGGER_UI =
    UPDATE_CHECK =
    APPLICATION_ROOT =
    SERVER_SENT_EVENTS =
    HTML_SANITIZATION =
    SQLALCHEMY_MAX_OVERFLOW =
    SQLALCHEMY_POOL_PRE_PING =
    SAFE_MODE =
    [oauth]
    OAUTH_CLIENT_ID =
    OAUTH_CLIENT_SECRET =
    [extra]
```
6. Kubernetes pod starts perfectly fine and falls back to env variables for config values.

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
Hmm you could possibly overload list indexing in ServerConfig. PR welcome for this if you have the time.
