### ISSUE TITLE
Initial database migration fails on Windows: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')

### ISSUE THREAD

**Issue by Jus-Codin** [CTFd/CTFd#2600]
**Environment**:

- CTFd Version/Commit: 3.7.3
- Operating System: Windows 11, Docker Desktop (WSL2)

**What happened?**

When starting up CTFd using `docker compose up` for the first time, the `ctfd-1` service errors out during the database migration. The specific migration causing the issue is [add_brackets_table.py](https://github.com/CTFd/CTFd/blob/edbc1e1ecb26576da1ce6349094a73e688ea9354/migrations/versions/9889b8c53673_add_brackets_table.py#L32). The `brackets` table is created before this error occurs which results in the error shown in #2556 when the service restarts. It must be noted that if the fix in https://github.com/CTFd/CTFd/issues/2556#issuecomment-2293569821 is done, the exact same query will work on the second run and allow the server to start successfully.

This issue only seems to occur on Windows, as it worked perfectly fine on Ubuntu when I tested it.

Based on the error messages, my guess is somehow MariaDB is not a fan of running on WSL2, but I was unable to pinpoint the exact issue causing this error. Some potentially related issues I could find online include:
- https://stackoverflow.com/questions/70784437/innodb-preallocating-147456-bytes-for-file-xxx-ibd-failed-with-error-2
- https://jira.mariadb.org/browse/MDEV-26381

Various online sources also suggest increasing max packet size and timeout of the database, but considering the simplicity and speed of the query I highly doubt that it is the correct fix here.

A potential workaround for this issue is mentioned in https://github.com/CTFd/CTFd/issues/2556#issuecomment-2293569821, where we just check if the `brackets` table and `bracket_id` column is added to the database. Since the services restarts on errors, the migrations will run again and work the second time round.

<details>
<summary>ctfd-1 Logs:</summary>

```
2024-09-19 20:04:38 Waiting for db to be ready
2024-09-19 20:04:44 ......db is ready
2024-09-19 20:04:48 INFO  [alembic.runtime.migration] Context impl MySQLImpl.
2024-09-19 20:04:48 INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2024-09-19 20:04:49 INFO  [alembic.runtime.migration] Running upgrade  -> 8369118943a1, Initial Revision
2024-09-19 20:04:50 INFO  [alembic.runtime.migration] Running upgrade 8369118943a1 -> 4e4d5a9ea000, Add type to awards
2024-09-19 20:04:50 INFO  [alembic.runtime.migration] Running upgrade 4e4d5a9ea000 -> b5551cd26764, Add captain column to Teams
2024-09-19 20:04:50 INFO  [alembic.runtime.migration] Running upgrade b5551cd26764 -> b295b033364d, Add ondelete cascade to foreign keys
2024-09-19 20:04:51 INFO  [alembic.runtime.migration] Running upgrade b295b033364d -> 080d29b15cd3, Add Tokens table to store user access tokens
2024-09-19 20:04:51 INFO  [alembic.runtime.migration] Running upgrade 080d29b15cd3 -> a03403986a32, add theme code injections to configs
2024-09-19 20:04:51 INFO  [alembic.runtime.migration] Running upgrade a03403986a32 -> 1093835a1051, Add default email templates
2024-09-19 20:04:51 INFO  [alembic.runtime.migration] Running upgrade 1093835a1051 -> 0366ba6575ca, Add table for comments
2024-09-19 20:04:52 INFO  [alembic.runtime.migration] Running upgrade 0366ba6575ca -> 75e8ab9a0014, Add Fields and FieldEntries tables
2024-09-19 20:04:52 INFO  [alembic.runtime.migration] Running upgrade 75e8ab9a0014 -> 07dfbe5e1edc, Add format to Pages
2024-09-19 20:04:52 INFO  [alembic.runtime.migration] Running upgrade 07dfbe5e1edc -> ef87d69ec29a, Add topics and challenge_topics tables
2024-09-19 20:04:52 INFO  [alembic.runtime.migration] Running upgrade ef87d69ec29a -> 6012fe8de495, Add connection_info column to Challenges
2024-09-19 20:04:52 INFO  [alembic.runtime.migration] Running upgrade 6012fe8de495 -> 4d3c1b59d011, Add next_id to Challenges table
2024-09-19 20:04:52 INFO  [alembic.runtime.migration] Running upgrade 4d3c1b59d011 -> 46a278193a94, Enable millisecond precision in MySQL datetime
2024-09-19 20:04:52 INFO  [alembic.runtime.migration] Running upgrade 46a278193a94 -> 0def790057c1, Add language column to Users table
2024-09-19 20:04:52 INFO  [alembic.runtime.migration] Running upgrade 0def790057c1 -> 9e6f6578ca84, Add description column to tokens table
2024-09-19 20:04:52 INFO  [alembic.runtime.migration] Running upgrade 9e6f6578ca84 -> 5c4996aeb2cb, Add sha1sum field to Files
2024-09-19 20:04:52 INFO  [alembic.runtime.migration] Running upgrade 5c4996aeb2cb -> 9889b8c53673, Add Brackets table
2024-09-19 20:04:52 Traceback (most recent call last):
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
2024-09-19 20:04:52     self.dialect.do_execute(
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2024-09-19 20:04:52     cursor.execute(statement, parameters)
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/pymysql/cursors.py", line 148, in execute
2024-09-19 20:04:52     result = self._query(query)
2024-09-19 20:04:52              ^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/pymysql/cursors.py", line 310, in _query
2024-09-19 20:04:52     conn.query(q)
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 548, in query
2024-09-19 20:04:52     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2024-09-19 20:04:52                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_query_result
2024-09-19 20:04:52     result.read()
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 1156, in read
2024-09-19 20:04:52     first_packet = self.connection._read_packet()
2024-09-19 20:04:52                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 692, in _read_packet
2024-09-19 20:04:52     packet_header = self._read_bytes(4)
2024-09-19 20:04:52                     ^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 748, in _read_bytes
2024-09-19 20:04:52     raise err.OperationalError(
2024-09-19 20:04:52 pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
2024-09-19 20:04:52 
2024-09-19 20:04:52 The above exception was the direct cause of the following exception:
2024-09-19 20:04:52 
2024-09-19 20:04:52 Traceback (most recent call last):
2024-09-19 20:04:52   File "/opt/venv/bin/flask", line 8, in <module>
2024-09-19 20:04:52     sys.exit(main())
2024-09-19 20:04:52              ^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/flask/cli.py", line 995, in main
2024-09-19 20:04:52     cli.main(args=sys.argv[1:])
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/flask/cli.py", line 601, in main
2024-09-19 20:04:52     return super().main(*args, **kwargs)
2024-09-19 20:04:52            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 782, in main
2024-09-19 20:04:52     rv = self.invoke(ctx)
2024-09-19 20:04:52          ^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1259, in invoke
2024-09-19 20:04:52     return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-09-19 20:04:52                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1259, in invoke
2024-09-19 20:04:52     return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-09-19 20:04:52                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1066, in invoke
2024-09-19 20:04:52     return ctx.invoke(self.callback, **ctx.params)
2024-09-19 20:04:52            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 610, in invoke
2024-09-19 20:04:52     return callback(*args, **kwargs)
2024-09-19 20:04:52            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/click/decorators.py", line 21, in new_func
2024-09-19 20:04:52     return f(get_current_context(), *args, **kwargs)
2024-09-19 20:04:52            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/flask/cli.py", line 444, in decorator
2024-09-19 20:04:52     with __ctx.ensure_object(ScriptInfo).load_app().app_context():
2024-09-19 20:04:52          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/flask/cli.py", line 411, in load_app
2024-09-19 20:04:52     app = locate_app(self, import_name, None, raise_if_not_found=False)
2024-09-19 20:04:52           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:52   File "/opt/venv/lib/python3.11/site-packages/flask/cli.py", line 260, in locate_app
2024-09-19 20:04:52     __import__(module_name)
2024-09-19 20:04:52   File "/opt/CTFd/wsgi.py", line 11, in <module>
2024-09-19 20:04:53     app = create_app()
2024-09-19 20:04:53           ^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/CTFd/CTFd/__init__.py", line 253, in create_app
2024-09-19 20:04:53     upgrade()
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/flask_migrate/__init__.py", line 96, in wrapped
2024-09-19 20:04:53     f(*args, **kwargs)
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/flask_migrate/__init__.py", line 271, in upgrade
2024-09-19 20:04:53     command.upgrade(config, revision, sql=sql, tag=tag)
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/command.py", line 298, in upgrade
2024-09-19 20:04:53     script.run_env()
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/script/base.py", line 489, in run_env
2024-09-19 20:04:53     util.load_python_file(self.dir, "env.py")
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
2024-09-19 20:04:53     module = load_module_py(module_id, path)
2024-09-19 20:04:53              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/util/compat.py", line 184, in load_module_py
2024-09-19 20:04:53     spec.loader.exec_module(module)
2024-09-19 20:04:53   File "/opt/CTFd/migrations/env.py", line 96, in <module>
2024-09-19 20:04:53     run_migrations_online()
2024-09-19 20:04:53   File "/opt/CTFd/migrations/env.py", line 90, in run_migrations_online
2024-09-19 20:04:53     context.run_migrations()
2024-09-19 20:04:53   File "<string>", line 8, in run_migrations
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
2024-09-19 20:04:53     self.get_context().run_migrations(**kw)
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/runtime/migration.py", line 522, in run_migrations
2024-09-19 20:04:53     step.migration_fn(**kw)
2024-09-19 20:04:53   File "/opt/CTFd/migrations/versions/9889b8c53673_add_brackets_table.py", line 32, in upgrade
2024-09-19 20:04:53     op.drop_column("teams", "bracket")
2024-09-19 20:04:53   File "<string>", line 8, in drop_column
2024-09-19 20:04:53   File "<string>", line 3, in drop_column
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/operations/ops.py", line 2049, in drop_column
2024-09-19 20:04:53     return operations.invoke(op)
2024-09-19 20:04:53            ^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/operations/base.py", line 373, in invoke
2024-09-19 20:04:53     return fn(self, operation)
2024-09-19 20:04:53            ^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/operations/toimpl.py", line 80, in drop_column
2024-09-19 20:04:53     operations.impl.drop_column(
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/ddl/impl.py", line 241, in drop_column
2024-09-19 20:04:53     self._exec(base.DropColumn(table_name, column, schema=schema))
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/alembic/ddl/impl.py", line 141, in _exec
2024-09-19 20:04:53     return conn.execute(construct, *multiparams, **params)
2024-09-19 20:04:53            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
2024-09-19 20:04:53     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
2024-09-19 20:04:53            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
2024-09-19 20:04:53     return connection._execute_ddl(
2024-09-19 20:04:53            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
2024-09-19 20:04:53     ret = self._execute_context(
2024-09-19 20:04:53           ^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1948, in _execute_context
2024-09-19 20:04:53     self._handle_dbapi_exception(
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2129, in _handle_dbapi_exception
2024-09-19 20:04:53     util.raise_(
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2024-09-19 20:04:53     raise exception
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
2024-09-19 20:04:53     self.dialect.do_execute(
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2024-09-19 20:04:53     cursor.execute(statement, parameters)
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/pymysql/cursors.py", line 148, in execute
2024-09-19 20:04:53     result = self._query(query)
2024-09-19 20:04:53              ^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/pymysql/cursors.py", line 310, in _query
2024-09-19 20:04:53     conn.query(q)
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 548, in query
2024-09-19 20:04:53     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2024-09-19 20:04:53                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_query_result
2024-09-19 20:04:53     result.read()
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 1156, in read
2024-09-19 20:04:53     first_packet = self.connection._read_packet()
2024-09-19 20:04:53                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 692, in _read_packet
2024-09-19 20:04:53     packet_header = self._read_bytes(4)
2024-09-19 20:04:53                     ^^^^^^^^^^^^^^^^^^^
2024-09-19 20:04:53   File "/opt/venv/lib/python3.11/site-packages/pymysql/connections.py", line 748, in _read_bytes
2024-09-19 20:04:53     raise err.OperationalError(
2024-09-19 20:04:53 sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
2024-09-19 20:04:53 [SQL: ALTER TABLE teams DROP COLUMN bracket]
2024-09-19 20:04:53 (Background on this error at: https://sqlalche.me/e/14/e3q8)
```

</details>

<details><summary>MariaDB Logs:</summary>

```
2024-09-19 11:22:22 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'ctfd' host: '172.18.0.4' (Got an error reading communication packets)
2024-09-19 11:22:26 5 [ERROR] InnoDB: preallocating 163840 bytes for file ./ctfd/teams.ibd failed with error 2
2024-09-19 11:22:26 0x7fef4c5f2640  InnoDB: Assertion failure in file ./storage/innobase/fil/fil0fil.cc line 625
InnoDB: Failing assertion: fsize != os_offset_t(-1)
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to https://jira.mariadb.org/
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mariadbd startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: https://mariadb.com/kb/en/library/innodb-recovery-modes/
InnoDB: about forcing recovery.
240919 11:22:26 [ERROR] mysqld got signal 6 ;
Sorry, we probably made a mistake, and this is a bug.

Your assistance in bug reporting will enable us to fix this for the next release.
To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.

Server version: 10.11.9-MariaDB-ubu2204-log source revision: 0e8fb977b00983d98c4c35e39bc1f36463095938
key_buffer_size=134217728
read_buffer_size=131072
max_used_connections=1
max_threads=153
thread_count=1
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 468063 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x7fef30000c68
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x7fef4c5f1cb8 thread_stack 0x49000
Printing to addr2line failed
mysqld(my_print_stacktrace+0x32)[0x56403a18c582]
mysqld(handle_fatal_signal+0x478)[0x564039c415c8]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fef71eed520]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7fef71f419fc]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7fef71eed476]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7fef71ed37f3]
mysqld(+0x6bdcb6)[0x564039848cb6]
mysqld(+0x6cd72c)[0x56403985872c]
mysqld(+0x6ce5a7)[0x5640398595a7]
mysqld(+0x6d0deb)[0x56403985bdeb]
mysqld(+0x6d17d5)[0x56403985c7d5]
mysqld(+0xf540e0)[0x56403a0df0e0]
mysqld(+0xf54d68)[0x56403a0dfd68]
mysqld(+0xeee5e2)[0x56403a0795e2]
mysqld(+0xe63e39)[0x564039feee39]
mysqld(+0xde46f5)[0x564039f6f6f5]
mysqld(+0xdda85e)[0x564039f6585e]
mysqld(_Z17mysql_alter_tableP3THDPK25st_mysql_const_lex_stringS3_P22Table_specification_stP10TABLE_LISTP13Recreate_infoP10Alter_infojP8st_orderbb+0x5546)[0x564039a9ab26]
mysqld(_ZN19Sql_cmd_alter_table7executeEP3THD+0x3fb)[0x564039b0ab3b]
mysqld(_Z21mysql_execute_commandP3THDb+0x4c83)[0x5640399d6683]
mysqld(_Z11mysql_parseP3THDPcjP12Parser_state+0x1e7)[0x5640399d79c7]
mysqld(_Z16dispatch_command19enum_server_commandP3THDPcjb+0xee5)[0x5640399d9bd5]
mysqld(_Z10do_commandP3THDb+0x138)[0x5640399dc108]
mysqld(_Z24do_handle_one_connectionP7CONNECTb+0x3bf)[0x564039b0590f]
mysqld(handle_one_connection+0x5d)[0x564039b05c5d]
mysqld(+0xcfc616)[0x564039e87616]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3)[0x7fef71f3fac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126850)[0x7fef71fd1850]

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0x7fef30010ac0): ALTER TABLE teams DROP COLUMN bracket

Connection ID (thread ID): 5
Status: NOT_KILLED

Optimizer switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=on,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=on,condition_pushdown_for_derived=on,split_materialized=on,condition_pushdown_for_subquery=on,rowid_filter=on,condition_pushdown_from_having=on,not_null_range_scan=off,hash_join_cardinality=off,cset_narrowing=off

The manual page at https://mariadb.com/kb/en/how-to-produce-a-full-stack-trace-for-mariadbd/ contains
information that should help you find out what is causing the crash.
Writing a core file...
Working directory at /var/lib/mysql
Resource Limits:
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             unlimited            unlimited            processes 
Max open files            1048576              1048576              files     
Max locked memory         unlimited            unlimited            bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       27095                27095                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
Core pattern: /mnt/wslg/dumps/core.%e

Kernel version: Linux version 5.15.153.1-microsoft-standard-WSL2 (root@941d701f84f1) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Fri Mar 29 23:14:13 UTC 2024

Fatal signal 11 while backtracing
```

</summary>

**Comment by ColdHeat** [comment]
Very odd, I wonder if this is perhaps fixed with a more recent version of MariaDB? I feel like the proposed fix for this is the wrong direction. The migration should run if the migration needs to be run and this failure here is outside of CTFd's scope.

**Comment by Jus-Codin** [comment]
Just found a related issue at https://github.com/orgs/firefly-iii/discussions/8500, seems that the issue is most likely the MariaDB image running in WSL2. For some reason if I use a named volume like so:
```yaml
db:
    volumes:
      - db-data:/var/lib/mysql
    
volumes:
  db-data:
 ```
 
 It now magically works on WSL2?
 
 I'm really confused as to why this is the case, but Docker on Windows has always had inconsistencies anyways.

**Comment by ColdHeat** [comment]
See https://github.com/CTFd/CTFd/pull/2601/commits/d659f43f8798bf563a1e1917b0364b92310b16e5 and https://github.com/CTFd/CTFd/issues/2600#issuecomment-2365065037 to get MariaDB working properly under Windows Docker Desktop with WSL2.

**Comment by Jus-Codin** [comment]
Update @ColdHeat! The bug has been [fixed](https://jira.mariadb.org/browse/MDEV-29260) in MariaDB >= 10.11.10 and now seems to work on WSL without any modifications. I think we can close this issue now.

**Comment by ColdHeat** [comment]
Great news, thank you!
