### ISSUE TITLE
Error in email verification with python3

### ISSUE THREAD

**Issue by Fxrh** [CTFd/CTFd#329]
I'm running CTFd 1.0.3 with python3. I turned on email verification and now, when registering an account, I get a 500 error and the following backtrace:

```
[2017-08-01 18:49:31,526] ERROR in app: Exception on /confirm [POST]
Traceback (most recent call last):
File "/opt/CTFd-1.0.3/venv/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/opt/CTFd-1.0.3/venv/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/CTFd-1.0.3/venv/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/CTFd-1.0.3/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/opt/CTFd-1.0.3/venv/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/CTFd-1.0.3/venv/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/CTFd-1.0.3/CTFd/auth.py", line 55, in confirm_user
utils.verify_email(team.email)
File "/opt/CTFd-1.0.3/CTFd/utils.py", line 499, in verify_email
token = s.sign(addr)
File "/opt/CTFd-1.0.3/venv/lib/python3.4/site-packages/itsdangerous.py", line 353, in sign
return value + want_bytes(self.sep) + self.get_signature(value)
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by ColdHeat** [comment]
I just took a look at this and I think this might be an issue in ItsDangerous (https://github.com/pallets/itsdangerous/issues/89).
