### ISSUE TITLE
registering e-mail address containing a '+'  results in HTTP-500

### ISSUE THREAD

**Issue by gumblr** [CTFd/CTFd#362]
Registering an e-mail address containing a plus sign ('+') results in an invalid registration link. If the registration link is entered in a browser, the framework responds with HTTP-500 ('
500
An Internal Server Error has occured')

sample data causing the error:
h+defect@example.com

sample data being parsed correctly:
h-correct@example.com

**Comment by ColdHeat** [comment]
Can you provide a stack trace? I wrote a test for this locally and it doesn't seem to be breaking...

**Comment by ColdHeat** [comment]
I also just tried this manualy on master. Are you running an up to date version of CTFd?

**Comment by Fxrh** [comment]
Hi, admin of the server is here. Due to some lokal changes, we are a few commits behind master (commit 62eb1b836c469ef34afd6e7b4b30465bf771d7bf + cherrypicked cfc87e7a2b2e962d37afe37e84191840aa4b3819). I guess the missing commit is 0aa0e9c5c1ffb23dbcc51fe692f2b427c8f03adf. Stacktrace:

```
Exception on /confirm/aCttcm1jZC5jdGYuZGFybXN0YWR0LmNjYy5kZUBjcnlzdGFsZG93bi5kZS5kb1NtSTBZeUpiLWRQ
WTRpMXBuLU9IMXIyUjA=
[GET]
Traceback (most recent call last):
File "/opt/ctfd-cda/venv2/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/opt/ctfd-cda/venv2/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/ctfd-cda/venv2/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/ctfd-cda/venv2/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/ctfd-cda/venv2/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/ctfd-cda/CTFd/auth.py", line 30, in confirm_user
return render_template('confirm.html', errors=['Your confirmation link seems wrong'])
File "/opt/ctfd-cda/venv2/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
context, ctx.app)
File "/opt/ctfd-cda/venv2/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
rv = template.render(context)
File "/opt/ctfd-cda/venv2/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/opt/ctfd-cda/venv2/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/ctfd-cda/CTFd/themes/original/templates/confirm.html", line 1, in top-level template code
{% extends "base.html" %}
File "/opt/ctfd-cda/CTFd/themes/original/templates/base.html", line 65, in top-level template code
{% block content %}
File "/opt/ctfd-cda/CTFd/themes/original/templates/confirm.html", line 39, in block "content"
We've sent a confirmation email to {{ team.email }}
File "/opt/ctfd-cda/venv2/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
return getattr(obj, attribute)
'team' is undefined
```

**Comment by ColdHeat** [comment]
You should be able to grab the latest [confirm.html](https://github.com/CTFd/CTFd/blob/master/CTFd/themes/original/templates/confirm.html) and replace your copy with it.

**Comment by Fxrh** [comment]
Thanks a lot!

**Comment by ColdHeat** [comment]
@Fxrh You should actually use this [confirm.html](https://github.com/CTFd/CTFd/pull/364/commits/9bdde9b66b186c4483ce54595c5c10c1bcb28a6f). 

Identified another issue while I was testing, sorry about that.
