### ISSUE TITLE
An Internal Server Error has occured

### ISSUE THREAD

**Issue by nia2202** [CTFd/CTFd#365]
Hi,

I am getting "500 An Internal Server Error has occured" after changing my password from the link provided by CTFd password reset feature. The new password is working though, its just that the error is annoying.

**Comment by ColdHeat** [comment]
Can you provide more details? A stack trace maybe?

**Comment by nia2202** [comment]
I deployed CTFd using gunicorn + nginx proxy and systemd. How do I produce stack trace? Thank you

**Comment by ColdHeat** [comment]
You should get something in `CTFd/logs/error.log` if you pulled the command from the Dockerfile. Or a stack trace should show up in gunicorn's logs as well. 

Or you can try to emulate the behavior using serve.py. 

But are you using the latest version of CTFd? Can you try updating first if you aren't?

**Comment by nia2202** [comment]
Ok, will check the errors later. Yes, I am using the latest version.

**Comment by nia2202** [comment]
Hi,

Here are my stack trace:
-------------------------------------------------------------------

[2017-08-25 05:45:31 +0000] [15625] [DEBUG] POST /reset_password/ImVkZW5lY2hvIi5ESUZLNVEuT3ZLcDdBSTVNODMzVnpheWFVbENVRm1HNVZJ%0A
[2017-08-25 05:45:32,324] ERROR in app: Exception on /reset_password/ImVkZW5lY2hvIi5ESUZLNVEuT3ZLcDdBSTVNODMzVnpheWFVbENVRm1HNVZJ
 [POST]
Traceback (most recent call last):
  File "/home/cbctf/ctfd/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cbctf/ctfd/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cbctf/ctfd/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cbctf/ctfd/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cbctf/ctfd/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/ctfd/CTFd/CTFd/auth.py", line 94, in reset_password
    logger.warn("[{date}] {ip} -  successful password reset for {username}".format(
NameError: global name 'logger' is not defined
[2017-08-25 05:45:32 +0000] [15623] [DEBUG] GET /static/user.css

**Comment by ColdHeat** [comment]
This bug was patched in master. Run `git pull` to update to the latest version.

**Comment by nia2202** [comment]
Git pull solved the issue. Thank you for your prompt response.

**Comment by AmrealAbhishek** [comment]
Am getting Internal Server error while using the luna theme.
