### ISSUE TITLE
Crash when non-auth visiting challenges page

### ISSUE THREAD

**Issue by doegox** [CTFd/CTFd#386]
Hi,

On an instance where there is no team yet, just challenges & hints, configured to have challenges viewable without being logged, when visiting the challenges page I get:

```
ERROR in app: Exception on /chals [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/CTFd/challenges.py", line 115, in chals
    unlocked_hints = set([u.itemid for u in Unlocks.query.filter_by(model='hints', teamid=session['id'])])
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: 'id'
```

Any idea?

**Comment by ColdHeat** [comment]
If you change:

https://github.com/CTFd/CTFd/blob/master/CTFd/challenges.py#L115

to 

`            unlocked_hints = set([u.itemid for u in Unlocks.query.filter_by(model='hints', teamid=session.get('id'))])`

It should work

**Comment by ColdHeat** [comment]
This should be fixed in master and 1.0.4 as well. I force updated the release but I think it's an issue important enough to warrant it.

**Comment by doegox** [comment]
This works fine now, thank you!

**Comment by ColdHeat** [comment]
You can update your copy of CTFd with `git pull` as well, if you haven't already 👍

**Comment by doegox** [comment]
yes that's what I did actually ;)
