### ISSUE TITLE
Exporting Error

### ISSUE THREAD

**Issue by Tiaonmmn** [CTFd/CTFd#387]
When I try to backup the CTFd data using the Admin Panel.I get an 500 error.And I'm using gunicorn to deploy it.
Here's the traceback:
```
~[2017-09-13 20:16:18,514] ERROR in app: Exception on /admin/export [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tiaonmmn/CTFd/CTFd/utils.py", line 224, in decorated_function
    return f(*args, **kwargs)
  File "/home/tiaonmmn/CTFd/CTFd/admin/__init__.py", line 82, in admin_export_ctf
    backup = export_ctf(segments.split(','))
  File "/home/tiaonmmn/CTFd/CTFd/utils.py", line 604, in export_ctf
    dataset.freeze(result, format='json', fileobj=result_file)
  File "/usr/local/lib/python3.5/dist-packages/dataset/freeze/app.py", line 125, in freeze
    return freeze_export(Export({}, kw), result=records)
  File "/usr/local/lib/python3.5/dist-packages/dataset/freeze/app.py", line 137, in freeze_export
    serializer.serialize()
  File "/usr/local/lib/python3.5/dist-packages/dataset/freeze/format/common.py", line 93, in serialize
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/dataset/freeze/format/fjson.py", line 61, in close
    fh.write(data)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by ColdHeat** [comment]
Seems like a dataset glitch. I would need a copy of your database in order to replicate and test this.

**Comment by ColdHeat** [comment]
It looks like dataset the freezing functionality into https://github.com/pudo/datafreeze. This will get integrated into CTFd for 1.0.5
