### ISSUE TITLE
Apache & CTFd Error mod_wsgi (500 Internal Server Error)

### ISSUE THREAD

**Issue by sugusrojo** [CTFd/CTFd#393]
Hello!
I have CTFd running perfect on port 4000 in my Ubuntu Server 16.04 
http://myserver.com:4000
But I want to be able to enter CTFd without pointing to a port (or using port 80 or 443)
http://myserver.com
The problem is that on port 80 I have Apache2 running.
How can I tell CTFd to work with Apache2 and port 80 or 443 at the same time? What changes do I have to make in Apache Config?
I read about mod_wsgi but I can not make work.

Files in my server:
/var/www/myserver.com/html/ctf.wsgi

> import sys
> sys.path.insert(0, '/var/www/myserver.com/html')
> 
> from CTFd import create_app
> application = create_app()

/etc/apache2/sites-available/myserver.com.conf

> <VirtualHost *:80>
> ServerName myserver.com
> ServerAlias www.myserver.com
> DocumentRoot /var/www/myserver.com/html
> WSGIScriptAlias / /var/www/myserver.com/html/ctf.wsgi
> ErrorLog ${APACHE_LOG_DIR}/error.log
> CustomLog ${APACHE_LOG_DIR}/access.log combined
> </VirtualHost>

Log Error Apache
```
[Thu Sep 21 23:35:23.536173 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749] mod_wsgi (pid=32498): Target WSGI script '/var/www/myserver.com/html/ctf.wsgi' cannot be loaded as Python module.
[Thu Sep 21 23:35:23.536501 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749] mod_wsgi (pid=32498): Exception occurred processing WSGI script '/var/www/myserver.com/html/ctf.wsgi'.
[Thu Sep 21 23:35:23.536528 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749] Traceback (most recent call last):
[Thu Sep 21 23:35:23.536545 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749]   File "/var/www/myserver.com/html/ctf.wsgi", line 5, in <module>
[Thu Sep 21 23:35:23.536590 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749]     application = create_app()
[Thu Sep 21 23:35:23.536609 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749]   File "/var/www/myserver.com/html/CTFd/__init__.py", line 49, in create_app
[Thu Sep 21 23:35:23.536656 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749]     app.config.from_object(config)
[Thu Sep 21 23:35:23.536667 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749]   File "/usr/local/lib/python2.7/dist-packages/flask/config.py", line 168, in from_object
[Thu Sep 21 23:35:23.536742 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749]     obj = import_string(obj)
[Thu Sep 21 23:35:23.536751 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749]   File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 418, in import_string
[Thu Sep 21 23:35:23.536873 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749]     __import__(import_name)
[Thu Sep 21 23:35:23.536881 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749]   File "/var/www/myserver.com/html/CTFd/config.py", line 5, in <module>
[Thu Sep 21 23:35:23.536924 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749]     with open('.ctfd_secret_key', 'a+b') as secret:
[Thu Sep 21 23:35:23.536941 2017] [wsgi:error] [pid 32498:tid 139645776221952] [client 201.231.154.86:55749] IOError: [Errno 13] Permission denied: '.ctfd_secret_key'
[Thu Sep 21 23:35:26.457529 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752] mod_wsgi (pid=32499): Target WSGI script '/var/www/myserver.com/html/ctf.wsgi' cannot be loaded as Python module.
[Thu Sep 21 23:35:26.457564 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752] mod_wsgi (pid=32499): Exception occurred processing WSGI script '/var/www/myserver.com/html/ctf.wsgi'.
[Thu Sep 21 23:35:26.457585 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752] Traceback (most recent call last):
[Thu Sep 21 23:35:26.457600 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752]   File "/var/www/myserver.com/html/ctf.wsgi", line 5, in <module>
[Thu Sep 21 23:35:26.457641 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752]     application = create_app()
[Thu Sep 21 23:35:26.457651 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752]   File "/var/www/myserver.com/html/CTFd/__init__.py", line 49, in create_app
[Thu Sep 21 23:35:26.457695 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752]     app.config.from_object(config)
[Thu Sep 21 23:35:26.457705 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752]   File "/usr/local/lib/python2.7/dist-packages/flask/config.py", line 168, in from_object
[Thu Sep 21 23:35:26.457773 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752]     obj = import_string(obj)
[Thu Sep 21 23:35:26.457782 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752]   File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 418, in import_string
[Thu Sep 21 23:35:26.457917 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752]     __import__(import_name)
[Thu Sep 21 23:35:26.457925 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752]   File "/var/www/myserver.com/html/CTFd/config.py", line 5, in <module>
[Thu Sep 21 23:35:26.457967 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752]     with open('.ctfd_secret_key', 'a+b') as secret:
[Thu Sep 21 23:35:26.457983 2017] [wsgi:error] [pid 32499:tid 139645818193664] [client 201.231.154.86:55752] IOError: [Errno 13] Permission denied: '.ctfd_secret_key'
[Thu Sep 21 23:35:26.796915 2017] [wsgi:error] [pid 32499:tid 139645809800960] [client 201.231.154.86:55753] mod_wsgi (pid=32499): Target WSGI script '/var/www/myserver.com/html/ctf.wsgi' cannot be loaded as Python module.
[Thu Sep 21 23:35:26.796943 2017] [wsgi:error] [pid 32499:tid 139645809800960] [client 201.231.154.86:55753] mod_wsgi (pid=32499): Exception occurred processing WSGI script '/var/www/myserver.com/html/ctf.wsgi'.
[Thu Sep 21 23:35:26.796958 2017] [wsgi:error] [pid 32499:tid 139645809800960] [client 201.231.154.86:55753] Traceback (most recent call last):
[Thu Sep 21 23:35:26.796975 2017] [wsgi:error] [pid 32499:tid 139645809800960] [client 201.231.154.86:55753]   File "/var/www/myserver.com/html/ctf.wsgi", line 5, in <module>
[Thu Sep 21 23:35:26.796994 2017] [wsgi:error] [pid 32499:tid 139645809800960] [client 201.231.154.86:55753]     application = create_app()
[Thu Sep 21 23:35:26.797001 2017] [wsgi:error] [pid 32499:tid 139645809800960] [client 201.231.154.86:55753]   File "/var/www/myserver.com/html/CTFd/__init__.py", line 49, in create_app
[Thu Sep 21 23:35:26.797010 2017] [wsgi:error] [pid 32499:tid 139645809800960] [client 201.231.154.86:55753]     app.config.from_object(config)
```

**Comment by ColdHeat** [comment]
You need to give the `www-data` user permission to read the `/var/www/myserver.com/html/CTFd/.ctfd_secret_key` file.
