### ISSUE TITLE
Using Challenge Type for polymorphic_on Breaks Challenge Type Plugin

### ISSUE THREAD

**Issue by ameserole** [CTFd/CTFd#451]
Using type for `polymorphic_on` in the Challenge model (https://github.com/CTFd/CTFd/blob/master/CTFd/models.py#L51-L56)  causes Challenge queries to break. Here is an example output:
```
127.0.0.1 - - [11/Nov/2017 23:13:03] "POST /admin/chals HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/messy/Documents/tamuctf-dev/CTFd/CTFd/utils.py", line 286, in decorated_function
    return f(*args, **kwargs)
  File "/home/messy/Documents/tamuctf-dev/CTFd/CTFd/admin/challenges.py", line 34, in admin_chals
    chals = Challenges.query.add_columns('id', 'type', 'name', 'value', 'description', 'category', 'hidden', 'max_attempts').order_by(Challenges.value).all()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 90, in instances
    util.raise_from_cause(err)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 78, in instances
    for row in fetch]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 643, in polymorphic_instance
    _instance = polymorphic_instances[discriminator]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/_collections.py", line 729, in __missing__
    self[key] = val = self.creator(key)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 627, in configure_subclass_mapper
    discriminator)
AssertionError: No such polymorphic_identity u'MultiQuestionChallenge' is defined
```

A possible solution for this would be to add a `discriminator` column and use that for `polymorphic_on` so that if a user wants to extend the Challenge model they can change the `polymorphic_identity` as well as the challenge type.

**Comment by ColdHeat** [comment]
I think you're missing how the polymorephic_identity works. 

Did you create a secondary table that specifies polymorephic_identity and type properly? Like in here: https://github.com/CTFd/DynamicValueChallenge/blob/master/__init__.py#L208-L215
Notice the polymorphic_identity and the type parameter.

**Comment by ameserole** [comment]
Ah ok that wasn't very clear to me initially.
Thanks for pointing that out!

**Comment by ColdHeat** [comment]
No problem! Let me make sure this is reflected in the wiki as well.
