### ISSUE TITLE
Importing CTFd-exported ZIP gives DateTime error

### ISSUE THREAD

**Issue by kylecook80** [CTFd/CTFd#498]
**Environment**:

  - CTFd Version/Commit: master
  - Operating System: Debian Testing
  - Web Browser and Version: N/A

**What happened?**
In trying to import a ZIP file that was previously exported with CTFd, an error is thrown stating "SQLite DateTime type only accepts Python"

**What did you expect to happen?**
I expected the data to import successfully

**How to reproduce your issue**
sudo python import.py ~/CTF-DATA.zip

**Any associated stack traces or error logs**
```
> sudo python import.py ~/CTF-DATA.zip 
/*\ CTFd has updated and must update the database! /*\
/*\ Please backup your database before proceeding! /*\
/*\ CTFd maintainers are not responsible for any data loss! /*\
Run database migrations (Y/N)y
 * Loaded module, <module 'CTFd.plugins.challenges' from '/var/www/ctfd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.keys' from '/var/www/ctfd/CTFd/plugins/keys/__init__.pyc'>
Traceback (most recent call last):
  File "import.py", line 9, in <module>
    import_ctf(sys.argv[1])
  File "/var/www/ctfd/CTFd/utils.py", line 802, in import_ctf
    table.insert(entry)
  File "/usr/local/lib/python2.7/dist-packages/dataset/table.py", line 80, in insert
    res = self.db.executable.execute(self.table.insert(row))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
    None, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 623, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/sqlite/base.py", line 610, in process
    raise TypeError("SQLite DateTime type only accepts Python "
sqlalchemy.exc.StatementError: (exceptions.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input. [SQL: u'INSERT INTO teams (name, email, password, website, affiliation, country, bracket, banned, verified, admin, joined) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)']
```

**Comment by ColdHeat** [comment]
How old is your CTFd instance? 

This should be resolved as of https://github.com/CTFd/CTFd/issues/246

**Comment by kylecook80** [comment]
Upon further inspection, the version of CTFd that the data was exported from was version 1.0.2. Do you think the database will upgrade cleanly to the latest version?

EDIT: Sorry! I didn't mean to post on the old issue

**Comment by ColdHeat** [comment]
Assuming the export has the alembic_version saved (meaning it is a full export) CTFd should have enough information to insert everything and then update itself. 

It is still simplest to only import into a completely empty database but the basic idea is that CTFd should import data, then realize that it needs to migrate, and then once you apply migrations it should update to latest.

**Comment by kylecook80** [comment]
Sorry, I am making this really difficult. That stacktrace was from 1.0.5. Here is one from master

```
> sudo python import.py ~/CTF-DATA.zip 
/*\ CTFd has updated and must update the database! /*\
/*\ Please backup your database before proceeding! /*\
/*\ CTFd maintainers are not responsible for any data loss! /*\
Run database migrations (Y/N)y
 * Loaded module, <module 'CTFd.plugins.challenges' from '/var/www/ctfd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.keys' from '/var/www/ctfd/CTFd/plugins/keys/__init__.pyc'>
Traceback (most recent call last):
  File "import.py", line 9, in <module>
    import_ctf(sys.argv[1])
  File "/var/www/ctfd/CTFd/utils.py", line 804, in import_ctf
    table.insert(entry)
  File "/usr/local/lib/python2.7/dist-packages/dataset/table.py", line 80, in insert
    res = self.db.executable.execute(self.table.insert(row))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
    None, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 623, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/sqlite/base.py", line 610, in process
    raise TypeError("SQLite DateTime type only accepts Python "
sqlalchemy.exc.StatementError: (exceptions.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input. [SQL: u'INSERT INTO teams (name, email, password, website, affiliation, country, bracket, banned, verified, admin, joined) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)']
```

**Comment by ColdHeat** [comment]
Can you open up the zip file and give me an example of what the importer is messing up on? 

CTFd should understand datetimes and try to convert them into real datetimes for import. 

Alternatively, you can just not use SQLite.

**Comment by kylecook80** [comment]
Also, I looked into alembic_version.json, and it is a blank file.

```
     {
    5       "id": 1,
    6       "name": "<redacted>",
    7       "email": "<redacted>",
    8       "password": "<redacted>",
    9       "website": null,
   10       "affiliation": null,
   11       "country": null,
   12       "bracket": null,
   13       "banned": false,
   14       "verified": false,
   15       "admin": true,
   16       "joined": "2017-08-21T19:26:42.037472"
   17     }
```

**Comment by ColdHeat** [comment]
If alembic_version is blank then its likely the import was not a full one or some other issue happened. 

Seems like the issue is the microseconds not being accepted. The proper format to accept this would probably be

```
v = datetime.datetime.strptime(v, '%Y-%m-%dT%H:%M:%S.%f')
```

I guess this is coming from a MySQL database and then you're trying to import it into SQLite? For simplicity I would just use MySQL for now so you can update your schema.

**Comment by ColdHeat** [comment]
You could also try to update the date format string to the one I posted above in `utils.py` to see if that allows you to import. That should work if you really want to use SQLite.

**Comment by kylecook80** [comment]
Thank you for the help! I think there was some miscommunication between me and another admin about how this was setup. I will try the suggestions above.

**Comment by ColdHeat** [comment]
CTFd exports should be able to go between databases. They should be viewed as a single portable file that can go between CTFd instances. 

I think there's enough here to warrant some kind of fix so I'll try to reproduce and come up with some general solution.

**Comment by kylecook80** [comment]
I doubled checked, and we definitely ran with SQLite. The production deployment ran on Debian 8.9 with version 3.8.7.1 of SQLite3. The exported data will not import into MySQL because of the following error:

```
sqlalchemy.exc.IntegrityError: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`ctfd`.`keys`, CONSTRAINT `keys_ibfk_1` FOREIGN KEY (`chal`) REFERENCES `challenges` (`id`))') [SQL: u'INSERT INTO `keys` (chal, key_type, flag, data) VALUES (%s, %s, %s, %s)'] [parameters: (29, 0, u'challenge-flag-here', None)]
```

**Comment by ColdHeat** [comment]
In that case I would probably see if you can modify the date format, or downgrade to 1.0.2, import, and then upgrade CTFd to master and run migrations.
