### ISSUE TITLE
Import: migration problems with ctf_theme

### ISSUE THREAD

**Issue by obilodeau** [CTFd/CTFd#615]
**Environment**:

  - CTFd Version/Commit: d17e5991938 (current master, on top of 1.1.4)
  - Operating System: Linux/Docker
  - Web Browser and Version: Chrome/latest

**What happened?**

When importing an old database into a new setup, the migration script to change `ctf_theme` from `original` to `core` never ran. It resulted in an instance that simply doesn't reply (not even an answer).

It was a partial import without keeping teams or scores. Maybe that's the reason?

**What did you expect to happen?**

Smooth import, working instance.

**How to reproduce your issue**

Spin a docker instance of a new CTFd, try to do a partial import of an old database.

Unfortunately, this is going to be a recurring problem for me since I'm giving a CTF workshop from time to time (killing and restarting a server) and I'm not willing to run an unpatched CTFd. I'm willing to help fix it if given pointers.

**Any associated stack traces or error logs**

```
[2018-04-16 02:42:47 +0000] [20] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 66, in handle
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1547, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/opt/CTFd/CTFd/utils.py", line 136, in general_error
    return render_template('errors/500.html'), 500
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: errors/500.html
```

**Comment by ColdHeat** [comment]
If the configuration values aren't important, then I would only import challenges if those are what's important because they should work just fine. 

To fix this, if you haven't already you should go into the database and modify `ctf_theme` to core manually. Hopefully this will be fixed when imports/exports gets rewritten for 2.0.

**Comment by ColdHeat** [comment]
Actually I think the real issue is that migrations didn't run which is covered by #567

**Comment by obilodeau** [comment]
Yes, the problem is that migrations didn't run. I'll restart my config and repopulate my instance, it's just going to be easier. Looking forward to #567.
