### ISSUE TITLE
After import: No such polymorphic_identity u'0' is defined

### ISSUE THREAD

**Issue by obilodeau** [CTFd/CTFd#616]
**Environment**:

  - CTFd Version/Commit: d17e5991938 (current master, on top of 1.1.4)
  - Operating System: Linux/Docker
  - Web Browser and Version: Chrome/latest

**What happened?**

When importing an old database into a new setup, and manually changing the theme to workaround #615, any page that involves challenges doesn't load.

**What did you expect to happen?**

Smooth import, working instance.

**How to reproduce your issue**

Spin a docker instance of a new CTFd, try to do a partial import of an old database.

The bug might be related to #613 (fixed by #614) since my backup file had entries with challenge id set to null. That may be a false alarm though, I haven't investigated.

**Any associated stack traces or error logs**

```
[2018-04-16 03:20:12,527] ERROR in app: Exception on /chals [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/CTFd/CTFd/challenges.py", line 121, in chals
    chals = Challenges.query.filter(or_(Challenges.hidden != True, Challenges.hidden == None)).order_by(Challenges.valu
e).all()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2726, in all
    return list(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 97, in instances
    util.raise_from_cause(err)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 78, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 722, in polymorphic_instance
    _instance = polymorphic_instances[discriminator]
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 729, in __missing__
    self[key] = val = self.creator(key)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 706, in configure_subclass_mapper
    discriminator)
AssertionError: No such polymorphic_identity u'0' is defined
```

**Comment by ColdHeat** [comment]
I get the feeling that your export is from awhile ago. If it was from before the challenge type plugin was introduced it might be before certain database columns were added. 

If that's the case then the simplest thing might be to use an old version of CTFd, import, and then upgrade. 

I'm closing this in favor of #567.

**Comment by obilodeau** [comment]
> I get the feeling that your export is from awhile ago. If it was from before the challenge type plugin was introduced it might be before certain database columns were added.

The version is: 1.0.3

> If that's the case then the simplest thing might be to use an old version of CTFd, import, and then upgrade.

Fair enough, at least I tried ;)

> I'm closing this in favor of #567.

If you need testers for this once ready, don't hesitate to ping me, I'll have my old database around and more recent ones.
