### ISSUE TITLE
CTFd container fails to load when MySQL password customized in docker-compose.yml

### ISSUE THREAD

**Issue by cryptax** [CTFd/CTFd#638]
**Environment**:

  - CTFd Version/Commit: 38416ce5c6e154aa06613e624b17d04761200cbb
  - Operating System: Linux Mint 18.3
  - Web Browser and Version: Firefox 60.0.1

**What happened?**

I have modified the SQL passwords in `docker-compose.yml` and then the CTFd container fails to load:

```
     - MYSQL_ROOT_PASSWORD=221cd0nwo8AQszm4ctfd
     - MYSQL_USER=ctfd
     - MYSQL_PASSWORD=tRQcn78avegtagtADSAD
```

**What did you expect to happen?**

I expected the docker container ctfd_ctfd_1 to load correctly and http://127.0.0.1:8000 to show up.

**How to reproduce your issue**

0. Stop any CTFd docker container and remove them (if any).
1. Clone the git repository
2. Modify docker-compose.yml with custom passwords as above for example. Also set WORKERS=1. It is easier as well to remove the `restart: always` so that the container does not continuously restart.
3. `docker-compose up -d`
4. You will see that http://127.0.0.1:8000 does not respond, that `docker ps` no longer lists ctfd_ctfd_1.

**Any associated stack traces or error logs**

The log of the ctfd_ctfd_1 container does not show much in my case:

```
$ docker logs ctfd_ctfd_1 
Waiting for db to be ready
.........db is ready
Starting CTFd
```

But in `.data/CTFd/logs/error.log` we see the following. See at the end a password error which suggests that the password has not been correctly set everywhere.

```
[2018-05-29 14:16:56 +0000] [30] [INFO] Starting gunicorn 19.7.1
[2018-05-29 14:16:56 +0000] [30] [INFO] Listening at: http://0.0.0.0:8000 (30)
[2018-05-29 14:16:56 +0000] [30] [INFO] Using worker: gevent
[2018-05-29 14:16:56 +0000] [40] [INFO] Booting worker with pid: 40
[2018-05-29 14:16:57 +0000] [40] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 364, in import_app
    app = eval(obj, vars(mod))
  File "<string>", line 1, in <module>
  File "/opt/CTFd/CTFd/__init__.py", line 103, in create_app
    if not database_exists(url):
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 477, in database_exists
    return bool(get_scalar_result(engine, text))
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 455, in get_scalar_result
    result_proxy = engine.execute(sql)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in execute
    connection = self.contextual_connect(close_with_result=True)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 782, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1186, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1183, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 667, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 936, in connect
    self._request_authentication()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1156, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
OperationalError: (pymysql.err.OperationalError) (1045, u"Access denied for user 'root'@'172.18.0.4' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)
[2018-05-29 14:16:57 +0000] [40] [INFO] Worker exiting (pid: 40)
[2018-05-29 14:16:57 +0000] [30] [INFO] Shutting down: Master
[2018-05-29 14:16:57 +0000] [30] [INFO] Reason: Worker failed to boot.
```

**Comment by ColdHeat** [comment]
I don't think you appropriately configured the DATABASE_URL environment variable.

**Comment by cryptax** [comment]
I didn't modify it. (closing the bug a bit fast no?)

**Comment by ColdHeat** [comment]
DATABASE_URL is how CTFd identifies how to connect to the database. If it's incorrect then CTFd will not be able to connect to the database. 

The issues tracker isn't really for support like this because it is meant for actual issues where something is wrong with CTFd or project milestones. This is covered in the [wiki](https://github.com/CTFd/CTFd/wiki) and the [CTFd Slack](https://slack.ctfd.io/) is better suited for issues like this.

**Comment by cryptax** [comment]
> DATABASE_URL is how CTFd identifies how to connect to the database. If it's incorrect then CTFd will not be able to connect to the database.

I understand now. You need to put the password **both** in MYSQL_ROOT_PASSWORD and in  DATABASE_URL

>The issues tracker isn't really for support like this because it is meant for actual issues where something is wrong with CTFd or project milestones.

I won't comment for this one, as it is my error. :(
For the other 2,  #637 and #636, I find you have been closing them too early, as to my understanding they are bugs of CTFd.
Nevertheless, I thank you for your support. :+1: 

> This is covered in the wiki and the CTFd Slack is better suited for issues like this.

For this precise issue, when you have time, I suggest modifying the doc to include the password must be set at both places (DATABASE_URL and MYSQL_ROOT_PASSWORD), because it is not intuitive to write twice the same things, I would have though DATABASE_URL use the MYSQL_ROOT_PASSWORD or something like that.
