### ISSUE TITLE
Error with use mysql 

### ISSUE THREAD

**Issue by williamnaltchadjian** [CTFd/CTFd#688]
**Environment**:

  - CTFd Version/Commit: 
    I'm using image from dockerhub ctfd/ctfd 
  - Operating System:
  - Web Browser and Version:

**What happened?**

```Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    app = create_app()
  File "/opt/CTFd/CTFd/__init__.py", line 118, in create_app
    if not database_exists(url):
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 468, in database_exists
    engine = sa.create_engine(url)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 81, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 102, in dbapi
    return __import__('MySQLdb')
ImportError: No module named MySQLdb
```

**What did you expect to happen?**

**How to reproduce your issue**
When running ctfd via docker run, I get the error
docker run -p 8000:8000 -e DATABASE_URL='mysql://user:password@myserver:3306/ctfd' ctfd/ctfd

**Any associated stack traces or error logs**

**Comment by grantdexter** [comment]
Also seeing this issue on a linux ec2 instance when creating engine for rds instance:
File "myfile.py", line 6, in <module>
    db_connect = create_engine('mysql+mysqldb://[removed-user]:[removed-password]@[removed-host-rds-instance]/[removed-db-name]')
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 425, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 81, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 102, in dbapi
    return __import__('MySQLdb')
ImportError: No module named MySQLdb

**Comment by ColdHeat** [comment]
CTFd doesn't install MySQLdb automatically because it is preferred to use pymysql. This is covered in https://github.com/CTFd/CTFd/wiki/Advanced-Deployment#database
