### ISSUE TITLE
SQLAlchemy throws an error when creating Docker container

### ISSUE THREAD

**Issue by sa7mon** [CTFd/CTFd#711]
**Environment**:

  - CTFd Version/Commit: Latest Docker
  - Operating System: Windows 8.1
  - Web Browser and Version: Firefox 62.0

**What happened?**
On a Windows 8.1 machine with Docker freshly installed, running `docker run` throws an error and hangs without creating a container.

**What did you expect to happen?**
For there to not be an error and a container to be created.

**How to reproduce your issue**
Run the following command `docker run -p 8000:8000 -it ctfd/ctfd`

**Any associated stack traces or error logs**
```
$ docker run -p 8000:8000 -it ctfd/ctfd
Unable to find image 'ctfd/ctfd:latest' locally
latest: Pulling from ctfd/ctfd
4fe2ade4980c: Pull complete
1b23fa3ccba5: Pull complete
b714494d7662: Pull complete
bbcb3ecc1c68: Pull complete
ffbdc8037c59: Pull complete
ac25d08e3fe6: Pull complete
3e65f7130801: Pull complete
836323b47565: Pull complete
Digest: sha256:a8d45989333f3bc4a3e5cfb34b746345383d0c9a596a5882b77bda0b7efaf692
Status: Downloaded newer image for ctfd/ctfd:latest
sh: 1: unknown operand
 * Loaded module, <module 'CTFd.plugins.keys' from '/opt/CTFd/CTFd/plugins/keys/__init__.py'>
 * Loaded module, <module 'CTFd.plugins.challenges' from '/opt/CTFd/CTFd/plugins/challenges/__init__.py'>
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/site-packages/alembic/util/compat.py", line 135, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 89, in <module>
    run_migrations_online()
  File "migrations/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/opt/CTFd/migrations/versions/cb3cfcc47e2f_base.py", line 29, in upgrade
    sa.PrimaryKeyConstraint('id')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python2.7/site-packages/alembic/operations/ops.py", line 1120, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python2.7/site-packages/alembic/operations/base.py", line 319, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 190, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 115, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table challenges already exists [SQL: u'\nCREATE TABLE challenges (\n\tid INTEGER NOT NULL, \n\tname VARCHAR(80), \n\tdescription
 VARCHAR(80), \n\tflags TEXT, \n\thidden BOOLEAN, \n\tPRIMARY KEY (id), \n\tCHECK (hidden IN (0, 1))\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
Starting CTFd
 * Loaded module, <module 'CTFd.plugins.keys' from '/opt/CTFd/CTFd/plugins/keys/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.challenges' from '/opt/CTFd/CTFd/plugins/challenges/__init__.pyc'>
```

**Comment by sa7mon** [comment]
FWIW this also happened on a Xubuntu 18 box

**Comment by ColdHeat** [comment]
Quite old issue. If this is still happening you can open another issue. I would recommend instead using `docker-compose`.

**Comment by miguelpduarte** [comment]
Just faced this issue when attempting a deployment using Docker to a cloud provider's infrastructure.
Would there be any possibility of adding a switch for "if the database and tables already exist fail silently"?

If several docker containers are created and they point at the same SQL server, all of them but the first will crash due to the `python manage.py db upgrade` erroring out.
