### ISSUE TITLE
2.0.0: Admin page and Dynamic challenges' delete function error. 

### ISSUE THREAD

**Issue by invom** [CTFd/CTFd#758]
**Environment**:

  - CTFd Version/Commit: **Docker ctfd/ctfd:finalize-2.0.0** and **mark-2.0.0**
  - Operating System: **Ubuntu14.04-Server**
  - Web Browser and Version:  **Chrome 70.0.3538.102 / Microsoft EdgeHTML 17.17134**

**What happened?**
I tried to delete the dynamic challenge. After confirming in the popup box, it does not take effect.   (Standard challenge is ok.)
Then I re-created a docker:mark-2.0.0 environment and found that I could not enter the admin page. 
The terminal's error message is below.

**What did you expect to happen?**

**How to reproduce your issue**
```bash
sudo docker run -p 8000:8000 -itd ctfd/ctfd:finalize-2.0.0
```

**Any associated stack traces or error logs**
![111.png](https://i.loli.net/2018/11/26/5bfc03d7cf5a3.png)
```
154.85.36.216 - - [26/Nov/2018:15:02:10 +0000] "DELETE /api/v1/challenges/1 HTTP/1.1" 500 37 "http://66.42.56.190:9999/admin/challenges/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
[2018-11-26 15:02:13,740] ERROR in app: Exception on /api/v1/challenges/1 [DELETE]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 98, in admins_only_wrapper
    return f(*args, **kwargs)
  File "/opt/CTFd/CTFd/api/v1/challenges.py", line 255, in delete
    chal_class.delete(challenge)
  File "/opt/CTFd/CTFd/plugins/dynamic_challenges/__init__.py", line 125, in delete
    files = Files.query.filter_by(challenge_id=challenge.id).all()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 1689, in filter_by
    for key, value in kwargs.items()]
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 383, in _entity_descriptor
    (description, key)
InvalidRequestError: Entity '<class 'CTFd.models.Files'>' has no property 'challenge_id'
```
```
154.85.36.216 - - [26/Nov/2018:14:44:35 +0000] "GET /admin/statistics HTTP/1.1" 500 4144 "http://66.42.56.190:9999/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
154.85.36.216 - - [26/Nov/2018:14:44:35 +0000] "GET /socket.io/?EIO=3&transport=polling&t=1543243473248-5 HTTP/1.1" 404 4195 "http://66.42.56.190:9999/admin/statistics" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
154.85.36.216 - - [26/Nov/2018:14:44:35 +0000] "GET /static/user.css HTTP/1.1" 200 0 "http://66.42.56.190:9999/admin/statistics" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
154.85.36.216 - - [26/Nov/2018:14:44:36 +0000] "GET /socket.io/?EIO=3&transport=polling&t=1543243473963-0 HTTP/1.1" 404 4195 "http://66.42.56.190:9999/admin/statistics" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
154.85.36.216 - - [26/Nov/2018:14:44:36 +0000] "GET /themes/core/static/img/favicon.ico HTTP/1.1" 200 0 "http://66.42.56.190:9999/admin/statistics" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
154.85.36.216 - - [26/Nov/2018:14:44:37 +0000] "GET /socket.io/?EIO=3&transport=polling&t=1543243474738-1 HTTP/1.1" 404 4195 "http://66.42.56.190:9999/admin/statistics" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
[2018-11-26 14:44:38,404] ERROR in app: Exception on /admin/statistics [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 98, in admins_only_wrapper
    return f(*args, **kwargs)
  File "/opt/CTFd/CTFd/admin/statistics.py", line 12, in statistics
    update_check()
  File "/opt/CTFd/CTFd/utils/updates/__init__.py", line 41, in update_check
    'ctf_id': sha256(name),
  File "/opt/CTFd/CTFd/utils/security/passwords.py", line 17, in sha256
    return hashlib.sha256(p).hexdigest()
TypeError: sha256() argument 1 must be string or buffer, not int
```

Many of my deployments have failed, and it seems that docker's deployment solution is not stable.

**Comment by ColdHeat** [comment]
Hi @invom, is your CTFs name just an integer? That's generally unexpected but should be a simple fix. 

What do you mean by your deployments have failed? Are you attempting to migrate existing deployments to 2.0.0?

**Comment by invom** [comment]
No migration, I am a new deployment.

**Comment by ColdHeat** [comment]
@invom This should be closed in master now. Can you pull and try?

**Comment by invom** [comment]
It's ok now. Thank you. 👍
