### ISSUE TITLE
CTFd Theme Internal Server Error

### ISSUE THREAD

**Issue by imchristianlowe** [CTFd/CTFd#892]
**Environment**:

  - CTFd Version/Commit: Newest Version/Commit
  - Operating System: Ubuntu 16.04
  - Web Browser and Version: Firefox

**What happened?**
I was presented with an Internal Server Error but the admin page looked fine.

**What did you expect to happen?**
The theme to show the the car hacking village theme

**How to reproduce your issue**
Setup an instance of CTFd and do a git pull for the Car Hacking Village Theme in the themes directory and run using nginx

**Any associated stack traces or error logs**
```
`[2019-03-03 19:48:50 +0000] [13695] [INFO] Starting gunicorn 19.9.0
[2019-03-03 19:48:50 +0000] [13695] [INFO] Listening at: http://0.0.0.0:8000 (13695)
[2019-03-03 19:48:50 +0000] [13695] [INFO] Using worker: sync
[2019-03-03 19:48:50 +0000] [13699] [INFO] Booting worker with pid: 13699
[2019-03-03 19:48:50 +0000] [13700] [INFO] Booting worker with pid: 13700
[2019-03-03 19:48:50 +0000] [13701] [INFO] Booting worker with pid: 13701
[2019-03-03 19:48:50 +0000] [13703] [INFO] Booting worker with pid: 13703
 * Loaded module, <module 'CTFd.plugins.challenges' from '/home/hax0r/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/home/hax0r/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/home/hax0r/CTFd/CTFd/plugins/flags/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.challenges' from '/home/hax0r/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.challenges' from '/home/hax0r/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.challenges' from '/home/hax0r/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/home/hax0r/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/home/hax0r/CTFd/CTFd/plugins/flags/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/home/hax0r/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/home/hax0r/CTFd/CTFd/plugins/flags/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/home/hax0r/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/home/hax0r/CTFd/CTFd/plugins/flags/__init__.pyc'>
[2019-03-03 19:49:03,935] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hax0r/CTFd/CTFd/views.py", line 179, in static_html
    return render_template('page.html', content=markdown(page.content))
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hax0r/CTFd/CTFd/themes/CTFd-Car-Hacking-Theme/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/hax0r/CTFd/CTFd/themes/CTFd-Car-Hacking-Theme/templates/base.html", line 4, in top-level template code
    <title>{{ ctf_name() }}</title>
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/jinja2/sandbox.py", line 425, in call
    if not __self.is_safe_callable(__obj):
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/jinja2/sandbox.py", line 338, in is_safe_callable
    return not (getattr(obj, 'unsafe_callable', False) or
UndefinedError: 'ctf_name' is undefined
[2019-03-03 19:49:03 +0000] [13699] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/engineio/middleware.py", line 67, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/home/hax0r/CTFd/CTFd/errors.py", line 16, in general_error
    return render_template('errors/500.html'), 500
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hax0r/CTFd/CTFd/themes/CTFd-Car-Hacking-Theme/templates/errors/500.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/hax0r/CTFd/CTFd/themes/CTFd-Car-Hacking-Theme/templates/base.html", line 4, in top-level template code
    <title>{{ ctf_name() }}</title>
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/jinja2/sandbox.py", line 425, in call
    if not __self.is_safe_callable(__obj):
  File "/home/hax0r/CTFd/ctfdenv/local/lib/python2.7/site-packages/jinja2/sandbox.py", line 338, in is_safe_callable
    return not (getattr(obj, 'unsafe_callable', False) or
UndefinedError: 'ctf_name' is undefined
`
```

**Comment by ColdHeat** [comment]
That theme is community supported and not something supported officially so this is probably better opened in the repo for that theme specifically. 

Officially supported themes (https://ctfd.io/store/) are updated for each CTFd version and we have some more in the works.
