### ISSUE TITLE
CTFd crashing on startup due to Redis

### ISSUE THREAD

**Issue by gszathmari** [CTFd/CTFd#906]
**Environment**:

  - CTFd Version/Commit: bf799fb22040a32bd2c8dcebecb010042782bc83
  - Operating System: Ubuntu 16.04.6
  - Web Browser and Version: Any

**What happened?**

We have upgraded our CTFd panels to the latest version, and they start throwing errors complaining about the lack of 'monkey patched socket library' when connecting to Redis. 

**What did you expect to happen?**

CTFd start normally

**How to reproduce your issue**

Enable Redis caching and start CTFd

**Any associated stack traces or error logs**

``` * Loaded module, <module 'CTFd.plugins.challenges' from '/home/ctfsyd/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/home/ctfsyd/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/home/ctfsyd/CTFd/CTFd/plugins/flags/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.challenges' from '/home/ctfsyd/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/home/ctfsyd/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/home/ctfsyd/CTFd/CTFd/plugins/flags/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.challenges' from '/home/ctfsyd/CTFd/CTFd/plugins/challenges/__init__.pyc'>
connect handler error
Traceback (most recent call last):
  File "/home/ctfsyd/.virtualenvs/ctfd/local/lib/python2.7/site-packages/engineio/server.py", line 505, in _trigger_event
    return self.handlers[event](*args)
  File "/home/ctfsyd/.virtualenvs/ctfd/local/lib/python2.7/site-packages/socketio/server.py", line 641, in _handle_eio_connect
    self.manager.initialize()
  File "/home/ctfsyd/.virtualenvs/ctfd/local/lib/python2.7/site-packages/socketio/redis_manager.py", line 64, in initialize
    'with ' + self.server.async_mode)
RuntimeError: Redis requires a monkey patched socket library to work with gevent
```

**Comment by ColdHeat** [comment]
Have you updated gevent? Are you using Python 3?

**Comment by gszathmari** [comment]
Thanks @ColdHeat for the quick response. We are running CTFd on these versions:

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
gevent==1.3.7
gevent-websocket==0.10.1

**Comment by ColdHeat** [comment]
Can you try using `gevent==1.4.0`?

Worst case you can try using the 2.1.0-dev branch as it cuts out the gevent-websocket library which has been a source of trouble.

**Comment by gszathmari** [comment]
Thank you for that. 
I just tried using `gevent==1.4.0` on Python 2 and 3 and I am now getting the following error:

```
[2019-03-19 20:22:59 -0400] [29537] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket&sid=f82039998aa94efcaf21552d875e36be
Traceback (most recent call last):
  File "/home/ctfsyd/.virtualenvs/ctfd3/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ctfsyd/.virtualenvs/ctfd3/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd3/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd3/lib/python3.5/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd3/lib/python3.5/site-packages/engineio/middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd3/lib/python3.5/site-packages/socketio/server.py", line 485, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd3/lib/python3.5/site-packages/engineio/server.py", line 340, in handle_request
    environ, start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd3/lib/python3.5/site-packages/engineio/socket.py", line 106, in handle_get_request
    start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd3/lib/python3.5/site-packages/engineio/socket.py", line 146, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd3/lib/python3.5/site-packages/engineio/async_drivers/gevent.py", line 35, in __call__
    raise RuntimeError('You need to use the gevent-websocket server. '
RuntimeError: You need to use the gevent-websocket server. See the Deployment section of the documentation for more information.
```

**Comment by gszathmari** [comment]
The error message is similar on Python 2:

```
RuntimeError: You need to use the gevent-websocket server. See the Deployment section of the documentation for more information.
[2019-03-19 20:25:20 +0000] [29638] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket&sid=324e2378e92e41e798a1c1929e4180f8
Traceback (most recent call last):
  File "/home/ctfsyd/.virtualenvs/ctfd2/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ctfsyd/.virtualenvs/ctfd2/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd2/local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd2/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd2/local/lib/python2.7/site-packages/engineio/middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd2/local/lib/python2.7/site-packages/socketio/server.py", line 485, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd2/local/lib/python2.7/site-packages/engineio/server.py", line 340, in handle_request
    environ, start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd2/local/lib/python2.7/site-packages/engineio/socket.py", line 106, in handle_get_request
    start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd2/local/lib/python2.7/site-packages/engineio/socket.py", line 146, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/ctfsyd/.virtualenvs/ctfd2/local/lib/python2.7/site-packages/engineio/async_drivers/gevent.py", line 35, in __call__
    raise RuntimeError('You need to use the gevent-websocket server. '
RuntimeError: You need to use the gevent-websocket server. See the Deployment section of the documentation for more information.
```

**Comment by ColdHeat** [comment]
You need to use the `geventwebsocket.gunicorn.workers.GeventWebSocketWorker` worker. Refer to the documentation: https://flask-socketio.readthedocs.io/en/latest/ 

I think this is resolved enough for me to close but you can continue asking questions.

**Comment by ColdHeat** [comment]
Keep in mind that Flask SocketIO will be removed in the next minor release.

**Comment by gszathmari** [comment]
Thanks mate, should I just upgrade to the 2.1.0-dev branch then?

**Comment by ColdHeat** [comment]
@gszathmari You can certainly try it but it's still under development and you might run into bugs. The migration process shouldn't significant if you do choose to stick with 2.0.4.

**Comment by gszathmari** [comment]
I will give it a shot, thank you for the help
